// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type Agent struct {
	ObjectReference

	Name string `json:"name"`
	ProjectID string `json:"project_id,omitempty"`
	Prompt string `json:"prompt,omitempty"`
	RepoURL string `json:"repo_url,omitempty"`
}

type AgentList struct {
	ListMeta
	Items []Agent `json:"items"`
}

func (l *AgentList) GetItems() []Agent { return l.Items }
func (l *AgentList) GetTotal() int                  { return l.Total }
func (l *AgentList) GetPage() int                   { return l.Page }
func (l *AgentList) GetSize() int                   { return l.Size }

type AgentBuilder struct {
	resource Agent
	errors   []error
}

func NewAgentBuilder() *AgentBuilder {
	return &AgentBuilder{}
}


func (b *AgentBuilder) Name(v string) *AgentBuilder {
	b.resource.Name = v
	return b
}

func (b *AgentBuilder) ProjectID(v string) *AgentBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *AgentBuilder) Prompt(v string) *AgentBuilder {
	b.resource.Prompt = v
	return b
}

func (b *AgentBuilder) RepoURL(v string) *AgentBuilder {
	b.resource.RepoURL = v
	return b
}


func (b *AgentBuilder) Build() (*Agent, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type AgentPatchBuilder struct {
	patch map[string]any
}

func NewAgentPatchBuilder() *AgentPatchBuilder {
	return &AgentPatchBuilder{patch: make(map[string]any)}
}


func (b *AgentPatchBuilder) Name(v string) *AgentPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *AgentPatchBuilder) ProjectID(v string) *AgentPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *AgentPatchBuilder) Prompt(v string) *AgentPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *AgentPatchBuilder) RepoURL(v string) *AgentPatchBuilder {
	b.patch["repo_url"] = v
	return b
}


func (b *AgentPatchBuilder) Build() map[string]any {
	return b.patch
}

