// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type Permission struct {
	ObjectReference

	ProjectID string `json:"project_id,omitempty"`
	Role string `json:"role"`
	SubjectName string `json:"subject_name"`
	SubjectType string `json:"subject_type"`
}

type PermissionList struct {
	ListMeta
	Items []Permission `json:"items"`
}

func (l *PermissionList) GetItems() []Permission { return l.Items }
func (l *PermissionList) GetTotal() int                  { return l.Total }
func (l *PermissionList) GetPage() int                   { return l.Page }
func (l *PermissionList) GetSize() int                   { return l.Size }

type PermissionBuilder struct {
	resource Permission
	errors   []error
}

func NewPermissionBuilder() *PermissionBuilder {
	return &PermissionBuilder{}
}


func (b *PermissionBuilder) ProjectID(v string) *PermissionBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *PermissionBuilder) Role(v string) *PermissionBuilder {
	b.resource.Role = v
	return b
}

func (b *PermissionBuilder) SubjectName(v string) *PermissionBuilder {
	b.resource.SubjectName = v
	return b
}

func (b *PermissionBuilder) SubjectType(v string) *PermissionBuilder {
	b.resource.SubjectType = v
	return b
}


func (b *PermissionBuilder) Build() (*Permission, error) {
	if b.resource.Role == "" {
		b.errors = append(b.errors, fmt.Errorf("role is required"))
	}
	if b.resource.SubjectName == "" {
		b.errors = append(b.errors, fmt.Errorf("subject_name is required"))
	}
	if b.resource.SubjectType == "" {
		b.errors = append(b.errors, fmt.Errorf("subject_type is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type PermissionPatchBuilder struct {
	patch map[string]any
}

func NewPermissionPatchBuilder() *PermissionPatchBuilder {
	return &PermissionPatchBuilder{patch: make(map[string]any)}
}


func (b *PermissionPatchBuilder) ProjectID(v string) *PermissionPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *PermissionPatchBuilder) Role(v string) *PermissionPatchBuilder {
	b.patch["role"] = v
	return b
}

func (b *PermissionPatchBuilder) SubjectName(v string) *PermissionPatchBuilder {
	b.patch["subject_name"] = v
	return b
}

func (b *PermissionPatchBuilder) SubjectType(v string) *PermissionPatchBuilder {
	b.patch["subject_type"] = v
	return b
}


func (b *PermissionPatchBuilder) Build() map[string]any {
	return b.patch
}

