// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type Project struct {
	ObjectReference

	Annotations string `json:"annotations,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Labels string `json:"labels,omitempty"`
	Name string `json:"name"`
	Status string `json:"status,omitempty"`
}

type ProjectList struct {
	ListMeta
	Items []Project `json:"items"`
}

func (l *ProjectList) GetItems() []Project { return l.Items }
func (l *ProjectList) GetTotal() int                  { return l.Total }
func (l *ProjectList) GetPage() int                   { return l.Page }
func (l *ProjectList) GetSize() int                   { return l.Size }

type ProjectBuilder struct {
	resource Project
	errors   []error
}

func NewProjectBuilder() *ProjectBuilder {
	return &ProjectBuilder{}
}


func (b *ProjectBuilder) Annotations(v string) *ProjectBuilder {
	b.resource.Annotations = v
	return b
}

func (b *ProjectBuilder) Description(v string) *ProjectBuilder {
	b.resource.Description = v
	return b
}

func (b *ProjectBuilder) DisplayName(v string) *ProjectBuilder {
	b.resource.DisplayName = v
	return b
}

func (b *ProjectBuilder) Labels(v string) *ProjectBuilder {
	b.resource.Labels = v
	return b
}

func (b *ProjectBuilder) Name(v string) *ProjectBuilder {
	b.resource.Name = v
	return b
}

func (b *ProjectBuilder) Status(v string) *ProjectBuilder {
	b.resource.Status = v
	return b
}


func (b *ProjectBuilder) Build() (*Project, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProjectPatchBuilder struct {
	patch map[string]any
}

func NewProjectPatchBuilder() *ProjectPatchBuilder {
	return &ProjectPatchBuilder{patch: make(map[string]any)}
}


func (b *ProjectPatchBuilder) Annotations(v string) *ProjectPatchBuilder {
	b.patch["annotations"] = v
	return b
}

func (b *ProjectPatchBuilder) Description(v string) *ProjectPatchBuilder {
	b.patch["description"] = v
	return b
}

func (b *ProjectPatchBuilder) DisplayName(v string) *ProjectPatchBuilder {
	b.patch["display_name"] = v
	return b
}

func (b *ProjectPatchBuilder) Labels(v string) *ProjectPatchBuilder {
	b.patch["labels"] = v
	return b
}

func (b *ProjectPatchBuilder) Name(v string) *ProjectPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ProjectPatchBuilder) Status(v string) *ProjectPatchBuilder {
	b.patch["status"] = v
	return b
}


func (b *ProjectPatchBuilder) Build() map[string]any {
	return b.patch
}

