// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
	"time"
)

type ProjectKey struct {
	ObjectReference

	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	KeyPrefix string `json:"key_prefix,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name string `json:"name"`
	PlaintextKey string `json:"plaintext_key,omitempty"`
	ProjectID string `json:"project_id,omitempty"`
}

type ProjectKeyList struct {
	ListMeta
	Items []ProjectKey `json:"items"`
}

func (l *ProjectKeyList) GetItems() []ProjectKey { return l.Items }
func (l *ProjectKeyList) GetTotal() int                  { return l.Total }
func (l *ProjectKeyList) GetPage() int                   { return l.Page }
func (l *ProjectKeyList) GetSize() int                   { return l.Size }

type ProjectKeyBuilder struct {
	resource ProjectKey
	errors   []error
}

func NewProjectKeyBuilder() *ProjectKeyBuilder {
	return &ProjectKeyBuilder{}
}


func (b *ProjectKeyBuilder) ExpiresAt(v *time.Time) *ProjectKeyBuilder {
	b.resource.ExpiresAt = v
	return b
}

func (b *ProjectKeyBuilder) KeyPrefix(v string) *ProjectKeyBuilder {
	b.resource.KeyPrefix = v
	return b
}

func (b *ProjectKeyBuilder) LastUsedAt(v *time.Time) *ProjectKeyBuilder {
	b.resource.LastUsedAt = v
	return b
}

func (b *ProjectKeyBuilder) Name(v string) *ProjectKeyBuilder {
	b.resource.Name = v
	return b
}

func (b *ProjectKeyBuilder) PlaintextKey(v string) *ProjectKeyBuilder {
	b.resource.PlaintextKey = v
	return b
}

func (b *ProjectKeyBuilder) ProjectID(v string) *ProjectKeyBuilder {
	b.resource.ProjectID = v
	return b
}


func (b *ProjectKeyBuilder) Build() (*ProjectKey, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProjectKeyPatchBuilder struct {
	patch map[string]any
}

func NewProjectKeyPatchBuilder() *ProjectKeyPatchBuilder {
	return &ProjectKeyPatchBuilder{patch: make(map[string]any)}
}


func (b *ProjectKeyPatchBuilder) Name(v string) *ProjectKeyPatchBuilder {
	b.patch["name"] = v
	return b
}


func (b *ProjectKeyPatchBuilder) Build() map[string]any {
	return b.patch
}

