// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type ProjectSettings struct {
	ObjectReference

	GroupAccess string `json:"group_access,omitempty"`
	ProjectID string `json:"project_id"`
	Repositories string `json:"repositories,omitempty"`
	RunnerSecrets string `json:"runner_secrets,omitempty"`
}

type ProjectSettingsList struct {
	ListMeta
	Items []ProjectSettings `json:"items"`
}

func (l *ProjectSettingsList) GetItems() []ProjectSettings { return l.Items }
func (l *ProjectSettingsList) GetTotal() int                  { return l.Total }
func (l *ProjectSettingsList) GetPage() int                   { return l.Page }
func (l *ProjectSettingsList) GetSize() int                   { return l.Size }

type ProjectSettingsBuilder struct {
	resource ProjectSettings
	errors   []error
}

func NewProjectSettingsBuilder() *ProjectSettingsBuilder {
	return &ProjectSettingsBuilder{}
}


func (b *ProjectSettingsBuilder) GroupAccess(v string) *ProjectSettingsBuilder {
	b.resource.GroupAccess = v
	return b
}

func (b *ProjectSettingsBuilder) ProjectID(v string) *ProjectSettingsBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *ProjectSettingsBuilder) Repositories(v string) *ProjectSettingsBuilder {
	b.resource.Repositories = v
	return b
}

func (b *ProjectSettingsBuilder) RunnerSecrets(v string) *ProjectSettingsBuilder {
	b.resource.RunnerSecrets = v
	return b
}


func (b *ProjectSettingsBuilder) Build() (*ProjectSettings, error) {
	if b.resource.ProjectID == "" {
		b.errors = append(b.errors, fmt.Errorf("project_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProjectSettingsPatchBuilder struct {
	patch map[string]any
}

func NewProjectSettingsPatchBuilder() *ProjectSettingsPatchBuilder {
	return &ProjectSettingsPatchBuilder{patch: make(map[string]any)}
}


func (b *ProjectSettingsPatchBuilder) GroupAccess(v string) *ProjectSettingsPatchBuilder {
	b.patch["group_access"] = v
	return b
}

func (b *ProjectSettingsPatchBuilder) ProjectID(v string) *ProjectSettingsPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *ProjectSettingsPatchBuilder) Repositories(v string) *ProjectSettingsPatchBuilder {
	b.patch["repositories"] = v
	return b
}

func (b *ProjectSettingsPatchBuilder) RunnerSecrets(v string) *ProjectSettingsPatchBuilder {
	b.patch["runner_secrets"] = v
	return b
}


func (b *ProjectSettingsPatchBuilder) Build() map[string]any {
	return b.patch
}

