// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type RepositoryRef struct {
	ObjectReference

	Branch string `json:"branch,omitempty"`
	Name string `json:"name"`
	Owner string `json:"owner,omitempty"`
	ProjectID string `json:"project_id,omitempty"`
	Provider string `json:"provider,omitempty"`
	RepoName string `json:"repo_name,omitempty"`
	URL string `json:"url"`
}

type RepositoryRefList struct {
	ListMeta
	Items []RepositoryRef `json:"items"`
}

func (l *RepositoryRefList) GetItems() []RepositoryRef { return l.Items }
func (l *RepositoryRefList) GetTotal() int                  { return l.Total }
func (l *RepositoryRefList) GetPage() int                   { return l.Page }
func (l *RepositoryRefList) GetSize() int                   { return l.Size }

type RepositoryRefBuilder struct {
	resource RepositoryRef
	errors   []error
}

func NewRepositoryRefBuilder() *RepositoryRefBuilder {
	return &RepositoryRefBuilder{}
}


func (b *RepositoryRefBuilder) Branch(v string) *RepositoryRefBuilder {
	b.resource.Branch = v
	return b
}

func (b *RepositoryRefBuilder) Name(v string) *RepositoryRefBuilder {
	b.resource.Name = v
	return b
}

func (b *RepositoryRefBuilder) Owner(v string) *RepositoryRefBuilder {
	b.resource.Owner = v
	return b
}

func (b *RepositoryRefBuilder) ProjectID(v string) *RepositoryRefBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *RepositoryRefBuilder) Provider(v string) *RepositoryRefBuilder {
	b.resource.Provider = v
	return b
}

func (b *RepositoryRefBuilder) RepoName(v string) *RepositoryRefBuilder {
	b.resource.RepoName = v
	return b
}

func (b *RepositoryRefBuilder) URL(v string) *RepositoryRefBuilder {
	b.resource.URL = v
	return b
}


func (b *RepositoryRefBuilder) Build() (*RepositoryRef, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.URL == "" {
		b.errors = append(b.errors, fmt.Errorf("url is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type RepositoryRefPatchBuilder struct {
	patch map[string]any
}

func NewRepositoryRefPatchBuilder() *RepositoryRefPatchBuilder {
	return &RepositoryRefPatchBuilder{patch: make(map[string]any)}
}


func (b *RepositoryRefPatchBuilder) Branch(v string) *RepositoryRefPatchBuilder {
	b.patch["branch"] = v
	return b
}

func (b *RepositoryRefPatchBuilder) Name(v string) *RepositoryRefPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *RepositoryRefPatchBuilder) Owner(v string) *RepositoryRefPatchBuilder {
	b.patch["owner"] = v
	return b
}

func (b *RepositoryRefPatchBuilder) ProjectID(v string) *RepositoryRefPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *RepositoryRefPatchBuilder) Provider(v string) *RepositoryRefPatchBuilder {
	b.patch["provider"] = v
	return b
}

func (b *RepositoryRefPatchBuilder) RepoName(v string) *RepositoryRefPatchBuilder {
	b.patch["repo_name"] = v
	return b
}

func (b *RepositoryRefPatchBuilder) URL(v string) *RepositoryRefPatchBuilder {
	b.patch["url"] = v
	return b
}


func (b *RepositoryRefPatchBuilder) Build() map[string]any {
	return b.patch
}

