// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
// Generated: 2026-02-14T22:04:03Z

package types

import (
	"errors"
	"fmt"
)

type Session struct {
	ObjectReference

	AssignedUserID  string `json:"assigned_user_id,omitempty"`
	CreatedByUserID string `json:"created_by_user_id,omitempty"`
	Name            string `json:"name"`
	Prompt          string `json:"prompt,omitempty"`
	RepoURL         string `json:"repo_url,omitempty"`
	WorkflowID      string `json:"workflow_id,omitempty"`
}

type SessionList struct {
	ListMeta
	Items []Session `json:"items"`
}

func (l *SessionList) GetItems() []Session { return l.Items }
func (l *SessionList) GetTotal() int       { return l.Total }
func (l *SessionList) GetPage() int        { return l.Page }
func (l *SessionList) GetSize() int        { return l.Size }

type SessionBuilder struct {
	resource Session
	errors   []error
}

func NewSessionBuilder() *SessionBuilder {
	return &SessionBuilder{}
}

func (b *SessionBuilder) AssignedUserID(v string) *SessionBuilder {
	b.resource.AssignedUserID = v
	return b
}

func (b *SessionBuilder) CreatedByUserID(v string) *SessionBuilder {
	b.resource.CreatedByUserID = v
	return b
}

func (b *SessionBuilder) Name(v string) *SessionBuilder {
	b.resource.Name = v
	return b
}

func (b *SessionBuilder) Prompt(v string) *SessionBuilder {
	b.resource.Prompt = v
	return b
}

func (b *SessionBuilder) RepoURL(v string) *SessionBuilder {
	b.resource.RepoURL = v
	return b
}

func (b *SessionBuilder) WorkflowID(v string) *SessionBuilder {
	b.resource.WorkflowID = v
	return b
}

func (b *SessionBuilder) Build() (*Session, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SessionPatchBuilder struct {
	patch map[string]any
}

func NewSessionPatchBuilder() *SessionPatchBuilder {
	return &SessionPatchBuilder{patch: make(map[string]any)}
}

func (b *SessionPatchBuilder) AssignedUserID(v string) *SessionPatchBuilder {
	b.patch["assigned_user_id"] = v
	return b
}

func (b *SessionPatchBuilder) CreatedByUserID(v string) *SessionPatchBuilder {
	b.patch["created_by_user_id"] = v
	return b
}

func (b *SessionPatchBuilder) Name(v string) *SessionPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *SessionPatchBuilder) Prompt(v string) *SessionPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *SessionPatchBuilder) RepoURL(v string) *SessionPatchBuilder {
	b.patch["repo_url"] = v
	return b
}

func (b *SessionPatchBuilder) WorkflowID(v string) *SessionPatchBuilder {
	b.patch["workflow_id"] = v
	return b
}

func (b *SessionPatchBuilder) Build() map[string]any {
	return b.patch
}
