// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
// Generated: 2026-02-14T22:04:03Z

package types

import (
	"errors"
	"fmt"
)

type Skill struct {
	ObjectReference

	Name    string `json:"name"`
	Prompt  string `json:"prompt,omitempty"`
	RepoURL string `json:"repo_url,omitempty"`
}

type SkillList struct {
	ListMeta
	Items []Skill `json:"items"`
}

func (l *SkillList) GetItems() []Skill { return l.Items }
func (l *SkillList) GetTotal() int     { return l.Total }
func (l *SkillList) GetPage() int      { return l.Page }
func (l *SkillList) GetSize() int      { return l.Size }

type SkillBuilder struct {
	resource Skill
	errors   []error
}

func NewSkillBuilder() *SkillBuilder {
	return &SkillBuilder{}
}

func (b *SkillBuilder) Name(v string) *SkillBuilder {
	b.resource.Name = v
	return b
}

func (b *SkillBuilder) Prompt(v string) *SkillBuilder {
	b.resource.Prompt = v
	return b
}

func (b *SkillBuilder) RepoURL(v string) *SkillBuilder {
	b.resource.RepoURL = v
	return b
}

func (b *SkillBuilder) Build() (*Skill, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SkillPatchBuilder struct {
	patch map[string]any
}

func NewSkillPatchBuilder() *SkillPatchBuilder {
	return &SkillPatchBuilder{patch: make(map[string]any)}
}

func (b *SkillPatchBuilder) Name(v string) *SkillPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *SkillPatchBuilder) Prompt(v string) *SkillPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *SkillPatchBuilder) RepoURL(v string) *SkillPatchBuilder {
	b.patch["repo_url"] = v
	return b
}

func (b *SkillPatchBuilder) Build() map[string]any {
	return b.patch
}
