// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type Task struct {
	ObjectReference

	Name string `json:"name"`
	ProjectID string `json:"project_id,omitempty"`
	Prompt string `json:"prompt,omitempty"`
	RepoURL string `json:"repo_url,omitempty"`
}

type TaskList struct {
	ListMeta
	Items []Task `json:"items"`
}

func (l *TaskList) GetItems() []Task { return l.Items }
func (l *TaskList) GetTotal() int                  { return l.Total }
func (l *TaskList) GetPage() int                   { return l.Page }
func (l *TaskList) GetSize() int                   { return l.Size }

type TaskBuilder struct {
	resource Task
	errors   []error
}

func NewTaskBuilder() *TaskBuilder {
	return &TaskBuilder{}
}


func (b *TaskBuilder) Name(v string) *TaskBuilder {
	b.resource.Name = v
	return b
}

func (b *TaskBuilder) ProjectID(v string) *TaskBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *TaskBuilder) Prompt(v string) *TaskBuilder {
	b.resource.Prompt = v
	return b
}

func (b *TaskBuilder) RepoURL(v string) *TaskBuilder {
	b.resource.RepoURL = v
	return b
}


func (b *TaskBuilder) Build() (*Task, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type TaskPatchBuilder struct {
	patch map[string]any
}

func NewTaskPatchBuilder() *TaskPatchBuilder {
	return &TaskPatchBuilder{patch: make(map[string]any)}
}


func (b *TaskPatchBuilder) Name(v string) *TaskPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *TaskPatchBuilder) ProjectID(v string) *TaskPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *TaskPatchBuilder) Prompt(v string) *TaskPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *TaskPatchBuilder) RepoURL(v string) *TaskPatchBuilder {
	b.patch["repo_url"] = v
	return b
}


func (b *TaskPatchBuilder) Build() map[string]any {
	return b.patch
}

