// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type User struct {
	ObjectReference

	Groups string `json:"groups,omitempty"`
	Name string `json:"name"`
	Username string `json:"username"`
}

type UserList struct {
	ListMeta
	Items []User `json:"items"`
}

func (l *UserList) GetItems() []User { return l.Items }
func (l *UserList) GetTotal() int                  { return l.Total }
func (l *UserList) GetPage() int                   { return l.Page }
func (l *UserList) GetSize() int                   { return l.Size }

type UserBuilder struct {
	resource User
	errors   []error
}

func NewUserBuilder() *UserBuilder {
	return &UserBuilder{}
}


func (b *UserBuilder) Groups(v string) *UserBuilder {
	b.resource.Groups = v
	return b
}

func (b *UserBuilder) Name(v string) *UserBuilder {
	b.resource.Name = v
	return b
}

func (b *UserBuilder) Username(v string) *UserBuilder {
	b.resource.Username = v
	return b
}


func (b *UserBuilder) Build() (*User, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.Username == "" {
		b.errors = append(b.errors, fmt.Errorf("username is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type UserPatchBuilder struct {
	patch map[string]any
}

func NewUserPatchBuilder() *UserPatchBuilder {
	return &UserPatchBuilder{patch: make(map[string]any)}
}


func (b *UserPatchBuilder) Groups(v string) *UserPatchBuilder {
	b.patch["groups"] = v
	return b
}

func (b *UserPatchBuilder) Name(v string) *UserPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *UserPatchBuilder) Username(v string) *UserPatchBuilder {
	b.patch["username"] = v
	return b
}


func (b *UserPatchBuilder) Build() map[string]any {
	return b.patch
}

