// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type Workflow struct {
	ObjectReference

	AgentID string `json:"agent_id,omitempty"`
	Branch string `json:"branch,omitempty"`
	Name string `json:"name"`
	Path string `json:"path,omitempty"`
	ProjectID string `json:"project_id,omitempty"`
	Prompt string `json:"prompt,omitempty"`
	RepoURL string `json:"repo_url,omitempty"`
}

type WorkflowList struct {
	ListMeta
	Items []Workflow `json:"items"`
}

func (l *WorkflowList) GetItems() []Workflow { return l.Items }
func (l *WorkflowList) GetTotal() int                  { return l.Total }
func (l *WorkflowList) GetPage() int                   { return l.Page }
func (l *WorkflowList) GetSize() int                   { return l.Size }

type WorkflowBuilder struct {
	resource Workflow
	errors   []error
}

func NewWorkflowBuilder() *WorkflowBuilder {
	return &WorkflowBuilder{}
}


func (b *WorkflowBuilder) AgentID(v string) *WorkflowBuilder {
	b.resource.AgentID = v
	return b
}

func (b *WorkflowBuilder) Branch(v string) *WorkflowBuilder {
	b.resource.Branch = v
	return b
}

func (b *WorkflowBuilder) Name(v string) *WorkflowBuilder {
	b.resource.Name = v
	return b
}

func (b *WorkflowBuilder) Path(v string) *WorkflowBuilder {
	b.resource.Path = v
	return b
}

func (b *WorkflowBuilder) ProjectID(v string) *WorkflowBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *WorkflowBuilder) Prompt(v string) *WorkflowBuilder {
	b.resource.Prompt = v
	return b
}

func (b *WorkflowBuilder) RepoURL(v string) *WorkflowBuilder {
	b.resource.RepoURL = v
	return b
}


func (b *WorkflowBuilder) Build() (*Workflow, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type WorkflowPatchBuilder struct {
	patch map[string]any
}

func NewWorkflowPatchBuilder() *WorkflowPatchBuilder {
	return &WorkflowPatchBuilder{patch: make(map[string]any)}
}


func (b *WorkflowPatchBuilder) AgentID(v string) *WorkflowPatchBuilder {
	b.patch["agent_id"] = v
	return b
}

func (b *WorkflowPatchBuilder) Branch(v string) *WorkflowPatchBuilder {
	b.patch["branch"] = v
	return b
}

func (b *WorkflowPatchBuilder) Name(v string) *WorkflowPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *WorkflowPatchBuilder) Path(v string) *WorkflowPatchBuilder {
	b.patch["path"] = v
	return b
}

func (b *WorkflowPatchBuilder) ProjectID(v string) *WorkflowPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *WorkflowPatchBuilder) Prompt(v string) *WorkflowPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *WorkflowPatchBuilder) RepoURL(v string) *WorkflowPatchBuilder {
	b.patch["repo_url"] = v
	return b
}


func (b *WorkflowPatchBuilder) Build() map[string]any {
	return b.patch
}

