// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type WorkflowTask struct {
	ObjectReference

	Position int32 `json:"position"`
	TaskID string `json:"task_id"`
	WorkflowID string `json:"workflow_id"`
}

type WorkflowTaskList struct {
	ListMeta
	Items []WorkflowTask `json:"items"`
}

func (l *WorkflowTaskList) GetItems() []WorkflowTask { return l.Items }
func (l *WorkflowTaskList) GetTotal() int                  { return l.Total }
func (l *WorkflowTaskList) GetPage() int                   { return l.Page }
func (l *WorkflowTaskList) GetSize() int                   { return l.Size }

type WorkflowTaskBuilder struct {
	resource WorkflowTask
	errors   []error
}

func NewWorkflowTaskBuilder() *WorkflowTaskBuilder {
	return &WorkflowTaskBuilder{}
}


func (b *WorkflowTaskBuilder) Position(v int32) *WorkflowTaskBuilder {
	b.resource.Position = v
	return b
}

func (b *WorkflowTaskBuilder) TaskID(v string) *WorkflowTaskBuilder {
	b.resource.TaskID = v
	return b
}

func (b *WorkflowTaskBuilder) WorkflowID(v string) *WorkflowTaskBuilder {
	b.resource.WorkflowID = v
	return b
}


func (b *WorkflowTaskBuilder) Build() (*WorkflowTask, error) {
	if b.resource.TaskID == "" {
		b.errors = append(b.errors, fmt.Errorf("task_id is required"))
	}
	if b.resource.WorkflowID == "" {
		b.errors = append(b.errors, fmt.Errorf("workflow_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type WorkflowTaskPatchBuilder struct {
	patch map[string]any
}

func NewWorkflowTaskPatchBuilder() *WorkflowTaskPatchBuilder {
	return &WorkflowTaskPatchBuilder{patch: make(map[string]any)}
}


func (b *WorkflowTaskPatchBuilder) Position(v int32) *WorkflowTaskPatchBuilder {
	b.patch["position"] = v
	return b
}

func (b *WorkflowTaskPatchBuilder) TaskID(v string) *WorkflowTaskPatchBuilder {
	b.patch["task_id"] = v
	return b
}

func (b *WorkflowTaskPatchBuilder) WorkflowID(v string) *WorkflowTaskPatchBuilder {
	b.patch["workflow_id"] = v
	return b
}


func (b *WorkflowTaskPatchBuilder) Build() map[string]any {
	return b.patch
}

