// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
// Generated: 2026-02-14T22:04:03Z

package types

import (
	"errors"
	"fmt"
)

type Workflow struct {
	ObjectReference

	AgentID string `json:"agent_id,omitempty"`
	Name    string `json:"name"`
	Prompt  string `json:"prompt,omitempty"`
	RepoURL string `json:"repo_url,omitempty"`
}

type WorkflowList struct {
	ListMeta
	Items []Workflow `json:"items"`
}

func (l *WorkflowList) GetItems() []Workflow { return l.Items }
func (l *WorkflowList) GetTotal() int        { return l.Total }
func (l *WorkflowList) GetPage() int         { return l.Page }
func (l *WorkflowList) GetSize() int         { return l.Size }

type WorkflowBuilder struct {
	resource Workflow
	errors   []error
}

func NewWorkflowBuilder() *WorkflowBuilder {
	return &WorkflowBuilder{}
}

func (b *WorkflowBuilder) AgentID(v string) *WorkflowBuilder {
	b.resource.AgentID = v
	return b
}

func (b *WorkflowBuilder) Name(v string) *WorkflowBuilder {
	b.resource.Name = v
	return b
}

func (b *WorkflowBuilder) Prompt(v string) *WorkflowBuilder {
	b.resource.Prompt = v
	return b
}

func (b *WorkflowBuilder) RepoURL(v string) *WorkflowBuilder {
	b.resource.RepoURL = v
	return b
}

func (b *WorkflowBuilder) Build() (*Workflow, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type WorkflowPatchBuilder struct {
	patch map[string]any
}

func NewWorkflowPatchBuilder() *WorkflowPatchBuilder {
	return &WorkflowPatchBuilder{patch: make(map[string]any)}
}

func (b *WorkflowPatchBuilder) AgentID(v string) *WorkflowPatchBuilder {
	b.patch["agent_id"] = v
	return b
}

func (b *WorkflowPatchBuilder) Name(v string) *WorkflowPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *WorkflowPatchBuilder) Prompt(v string) *WorkflowPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *WorkflowPatchBuilder) RepoURL(v string) *WorkflowPatchBuilder {
	b.patch["repo_url"] = v
	return b
}

func (b *WorkflowPatchBuilder) Build() map[string]any {
	return b.patch
}
