// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package types

import (
	"errors"
	"fmt"
)

type WorkflowSkill struct {
	ObjectReference

	Position int32 `json:"position"`
	SkillID string `json:"skill_id"`
	WorkflowID string `json:"workflow_id"`
}

type WorkflowSkillList struct {
	ListMeta
	Items []WorkflowSkill `json:"items"`
}

func (l *WorkflowSkillList) GetItems() []WorkflowSkill { return l.Items }
func (l *WorkflowSkillList) GetTotal() int                  { return l.Total }
func (l *WorkflowSkillList) GetPage() int                   { return l.Page }
func (l *WorkflowSkillList) GetSize() int                   { return l.Size }

type WorkflowSkillBuilder struct {
	resource WorkflowSkill
	errors   []error
}

func NewWorkflowSkillBuilder() *WorkflowSkillBuilder {
	return &WorkflowSkillBuilder{}
}


func (b *WorkflowSkillBuilder) Position(v int32) *WorkflowSkillBuilder {
	b.resource.Position = v
	return b
}

func (b *WorkflowSkillBuilder) SkillID(v string) *WorkflowSkillBuilder {
	b.resource.SkillID = v
	return b
}

func (b *WorkflowSkillBuilder) WorkflowID(v string) *WorkflowSkillBuilder {
	b.resource.WorkflowID = v
	return b
}


func (b *WorkflowSkillBuilder) Build() (*WorkflowSkill, error) {
	if b.resource.SkillID == "" {
		b.errors = append(b.errors, fmt.Errorf("skill_id is required"))
	}
	if b.resource.WorkflowID == "" {
		b.errors = append(b.errors, fmt.Errorf("workflow_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type WorkflowSkillPatchBuilder struct {
	patch map[string]any
}

func NewWorkflowSkillPatchBuilder() *WorkflowSkillPatchBuilder {
	return &WorkflowSkillPatchBuilder{patch: make(map[string]any)}
}


func (b *WorkflowSkillPatchBuilder) Position(v int32) *WorkflowSkillPatchBuilder {
	b.patch["position"] = v
	return b
}

func (b *WorkflowSkillPatchBuilder) SkillID(v string) *WorkflowSkillPatchBuilder {
	b.patch["skill_id"] = v
	return b
}

func (b *WorkflowSkillPatchBuilder) WorkflowID(v string) *WorkflowSkillPatchBuilder {
	b.patch["workflow_id"] = v
	return b
}


func (b *WorkflowSkillPatchBuilder) Build() map[string]any {
	return b.patch
}

