apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambient-api-server
spec:
  template:
    spec:
      containers:
        - name: api-server
          env:
            - name: AMBIENT_ENV
              value: production
