# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: f729ebc11ad1c453eeb0a679fa5c14eb1bc0096450cd18ca79e7c9b7b5c81acf
# Generated: 2026-03-05T04:28:57Z

from __future__ import annotations

from typing import Any, Callable, Iterator, TypeVar

T = TypeVar("T")


def paginate(fetch_page: Callable[..., Any], size: int = 100) -> Iterator[Any]:
    page = 1
    while True:
        result = fetch_page(page=page, size=size)
        yield from result.items
        if page * size >= result.total:
            break
        page += 1
