# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .project_key import ProjectKey, ProjectKeyList

if TYPE_CHECKING:
    from .client import AmbientClient


class ProjectKeyAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> ProjectKey:
        resp = self._client._request("POST", "/project_keys", json=data)
        return ProjectKey.from_dict(resp)

    def get(self, resource_id: str) -> ProjectKey:
        resp = self._client._request("GET", f"/project_keys/{resource_id}")
        return ProjectKey.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ProjectKeyList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/project_keys", params=params)
        return ProjectKeyList.from_dict(resp)
    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"/project_keys/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[ProjectKey]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
