# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
# Generated: 2026-02-14T22:04:03Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .session import Session, SessionList

if TYPE_CHECKING:
    from .client import AmbientClient


class SessionAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Session:
        resp = self._client._request("POST", "/sessions", json=data)
        return Session.from_dict(resp)

    def get(self, resource_id: str) -> Session:
        resp = self._client._request("GET", f"/sessions/{resource_id}")
        return Session.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> SessionList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/sessions", params=params)
        return SessionList.from_dict(resp)

    def update(self, resource_id: str, patch: Any) -> Session:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/sessions/{resource_id}", json=data)
        return Session.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Session]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
