# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Permission:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    project_id: str = ""
    role: str = ""
    subject_name: str = ""
    subject_type: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Permission:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            project_id=data.get("project_id", ""),
            role=data.get("role", ""),
            subject_name=data.get("subject_name", ""),
            subject_type=data.get("subject_type", ""),
        )

    @classmethod
    def builder(cls) -> PermissionBuilder:
        return PermissionBuilder()


@dataclass(frozen=True)
class PermissionList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[Permission] = ()

    @classmethod
    def from_dict(cls, data: dict) -> PermissionList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Permission.from_dict(item) for item in data.get("items", [])],
        )


class PermissionBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def project_id(self, value: str) -> PermissionBuilder:
        self._data["project_id"] = value
        return self

    def role(self, value: str) -> PermissionBuilder:
        self._data["role"] = value
        return self

    def subject_name(self, value: str) -> PermissionBuilder:
        self._data["subject_name"] = value
        return self

    def subject_type(self, value: str) -> PermissionBuilder:
        self._data["subject_type"] = value
        return self

    def build(self) -> dict:
        if "role" not in self._data:
            raise ValueError("role is required")
        if "subject_name" not in self._data:
            raise ValueError("subject_name is required")
        if "subject_type" not in self._data:
            raise ValueError("subject_type is required")
        return dict(self._data)


class PermissionPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def project_id(self, value: str) -> PermissionPatch:
        self._data["project_id"] = value
        return self

    def role(self, value: str) -> PermissionPatch:
        self._data["role"] = value
        return self

    def subject_name(self, value: str) -> PermissionPatch:
        self._data["subject_name"] = value
        return self

    def subject_type(self, value: str) -> PermissionPatch:
        self._data["subject_type"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

