# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class ProjectKey:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    key_prefix: str = ""
    last_used_at: Optional[datetime] = None
    name: str = ""
    plaintext_key: str = ""
    project_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ProjectKey:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            expires_at=_parse_datetime(data.get("expires_at")),
            key_prefix=data.get("key_prefix", ""),
            last_used_at=_parse_datetime(data.get("last_used_at")),
            name=data.get("name", ""),
            plaintext_key=data.get("plaintext_key", ""),
            project_id=data.get("project_id", ""),
        )

    @classmethod
    def builder(cls) -> ProjectKeyBuilder:
        return ProjectKeyBuilder()


@dataclass(frozen=True)
class ProjectKeyList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[ProjectKey] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectKeyList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[ProjectKey.from_dict(item) for item in data.get("items", [])],
        )


class ProjectKeyBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def expires_at(self, value: Optional[datetime]) -> ProjectKeyBuilder:
        self._data["expires_at"] = value
        return self

    def key_prefix(self, value: str) -> ProjectKeyBuilder:
        self._data["key_prefix"] = value
        return self

    def last_used_at(self, value: Optional[datetime]) -> ProjectKeyBuilder:
        self._data["last_used_at"] = value
        return self

    def name(self, value: str) -> ProjectKeyBuilder:
        self._data["name"] = value
        return self

    def plaintext_key(self, value: str) -> ProjectKeyBuilder:
        self._data["plaintext_key"] = value
        return self

    def project_id(self, value: str) -> ProjectKeyBuilder:
        self._data["project_id"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        return dict(self._data)


class ProjectKeyPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> ProjectKeyPatch:
        self._data["name"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

