# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class RepositoryRef:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    branch: str = ""
    name: str = ""
    owner: str = ""
    project_id: str = ""
    provider: str = ""
    repo_name: str = ""
    url: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> RepositoryRef:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            branch=data.get("branch", ""),
            name=data.get("name", ""),
            owner=data.get("owner", ""),
            project_id=data.get("project_id", ""),
            provider=data.get("provider", ""),
            repo_name=data.get("repo_name", ""),
            url=data.get("url", ""),
        )

    @classmethod
    def builder(cls) -> RepositoryRefBuilder:
        return RepositoryRefBuilder()


@dataclass(frozen=True)
class RepositoryRefList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[RepositoryRef] = ()

    @classmethod
    def from_dict(cls, data: dict) -> RepositoryRefList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[RepositoryRef.from_dict(item) for item in data.get("items", [])],
        )


class RepositoryRefBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def branch(self, value: str) -> RepositoryRefBuilder:
        self._data["branch"] = value
        return self

    def name(self, value: str) -> RepositoryRefBuilder:
        self._data["name"] = value
        return self

    def owner(self, value: str) -> RepositoryRefBuilder:
        self._data["owner"] = value
        return self

    def project_id(self, value: str) -> RepositoryRefBuilder:
        self._data["project_id"] = value
        return self

    def provider(self, value: str) -> RepositoryRefBuilder:
        self._data["provider"] = value
        return self

    def repo_name(self, value: str) -> RepositoryRefBuilder:
        self._data["repo_name"] = value
        return self

    def url(self, value: str) -> RepositoryRefBuilder:
        self._data["url"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "url" not in self._data:
            raise ValueError("url is required")
        return dict(self._data)


class RepositoryRefPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def branch(self, value: str) -> RepositoryRefPatch:
        self._data["branch"] = value
        return self

    def name(self, value: str) -> RepositoryRefPatch:
        self._data["name"] = value
        return self

    def owner(self, value: str) -> RepositoryRefPatch:
        self._data["owner"] = value
        return self

    def project_id(self, value: str) -> RepositoryRefPatch:
        self._data["project_id"] = value
        return self

    def provider(self, value: str) -> RepositoryRefPatch:
        self._data["provider"] = value
        return self

    def repo_name(self, value: str) -> RepositoryRefPatch:
        self._data["repo_name"] = value
        return self

    def url(self, value: str) -> RepositoryRefPatch:
        self._data["url"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

