# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
# Generated: 2026-02-14T22:04:03Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Skill:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    name: str = ""
    prompt: str = ""
    repo_url: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Skill:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            name=data.get("name", ""),
            prompt=data.get("prompt", ""),
            repo_url=data.get("repo_url", ""),
        )

    @classmethod
    def builder(cls) -> SkillBuilder:
        return SkillBuilder()


@dataclass(frozen=True)
class SkillList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[Skill] = ()

    @classmethod
    def from_dict(cls, data: dict) -> SkillList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Skill.from_dict(item) for item in data.get("items", [])],
        )


class SkillBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> SkillBuilder:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> SkillBuilder:
        self._data["prompt"] = value
        return self

    def repo_url(self, value: str) -> SkillBuilder:
        self._data["repo_url"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        return dict(self._data)


class SkillPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> SkillPatch:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> SkillPatch:
        self._data["prompt"] = value
        return self

    def repo_url(self, value: str) -> SkillPatch:
        self._data["repo_url"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
