# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
# Generated: 2026-02-14T22:04:03Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class User:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    name: str = ""
    username: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> User:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            name=data.get("name", ""),
            username=data.get("username", ""),
        )

    @classmethod
    def builder(cls) -> UserBuilder:
        return UserBuilder()


@dataclass(frozen=True)
class UserList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[User] = ()

    @classmethod
    def from_dict(cls, data: dict) -> UserList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[User.from_dict(item) for item in data.get("items", [])],
        )


class UserBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> UserBuilder:
        self._data["name"] = value
        return self

    def username(self, value: str) -> UserBuilder:
        self._data["username"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "username" not in self._data:
            raise ValueError("username is required")
        return dict(self._data)


class UserPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> UserPatch:
        self._data["name"] = value
        return self

    def username(self, value: str) -> UserPatch:
        self._data["username"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
