/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProjectSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectSettings{}

// ProjectSettings struct for ProjectSettings
type ProjectSettings struct {
	Id            *string    `json:"id,omitempty"`
	Kind          *string    `json:"kind,omitempty"`
	Href          *string    `json:"href,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	ProjectId     string     `json:"project_id"`
	GroupAccess   *string    `json:"group_access,omitempty"`
	RunnerSecrets *string    `json:"runner_secrets,omitempty"`
	Repositories  *string    `json:"repositories,omitempty"`
}

type _ProjectSettings ProjectSettings

// NewProjectSettings instantiates a new ProjectSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectSettings(projectId string) *ProjectSettings {
	this := ProjectSettings{}
	this.ProjectId = projectId
	return &this
}

// NewProjectSettingsWithDefaults instantiates a new ProjectSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectSettingsWithDefaults() *ProjectSettings {
	this := ProjectSettings{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectSettings) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectSettings) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProjectSettings) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ProjectSettings) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ProjectSettings) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ProjectSettings) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ProjectSettings) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ProjectSettings) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ProjectSettings) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectSettings) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectSettings) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ProjectSettings) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectSettings) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectSettings) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProjectSettings) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetProjectId returns the ProjectId field value
func (o *ProjectSettings) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProjectSettings) SetProjectId(v string) {
	o.ProjectId = v
}

// GetGroupAccess returns the GroupAccess field value if set, zero value otherwise.
func (o *ProjectSettings) GetGroupAccess() string {
	if o == nil || IsNil(o.GroupAccess) {
		var ret string
		return ret
	}
	return *o.GroupAccess
}

// GetGroupAccessOk returns a tuple with the GroupAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetGroupAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GroupAccess) {
		return nil, false
	}
	return o.GroupAccess, true
}

// HasGroupAccess returns a boolean if a field has been set.
func (o *ProjectSettings) HasGroupAccess() bool {
	if o != nil && !IsNil(o.GroupAccess) {
		return true
	}

	return false
}

// SetGroupAccess gets a reference to the given string and assigns it to the GroupAccess field.
func (o *ProjectSettings) SetGroupAccess(v string) {
	o.GroupAccess = &v
}

// GetRunnerSecrets returns the RunnerSecrets field value if set, zero value otherwise.
func (o *ProjectSettings) GetRunnerSecrets() string {
	if o == nil || IsNil(o.RunnerSecrets) {
		var ret string
		return ret
	}
	return *o.RunnerSecrets
}

// GetRunnerSecretsOk returns a tuple with the RunnerSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetRunnerSecretsOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerSecrets) {
		return nil, false
	}
	return o.RunnerSecrets, true
}

// HasRunnerSecrets returns a boolean if a field has been set.
func (o *ProjectSettings) HasRunnerSecrets() bool {
	if o != nil && !IsNil(o.RunnerSecrets) {
		return true
	}

	return false
}

// SetRunnerSecrets gets a reference to the given string and assigns it to the RunnerSecrets field.
func (o *ProjectSettings) SetRunnerSecrets(v string) {
	o.RunnerSecrets = &v
}

// GetRepositories returns the Repositories field value if set, zero value otherwise.
func (o *ProjectSettings) GetRepositories() string {
	if o == nil || IsNil(o.Repositories) {
		var ret string
		return ret
	}
	return *o.Repositories
}

// GetRepositoriesOk returns a tuple with the Repositories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettings) GetRepositoriesOk() (*string, bool) {
	if o == nil || IsNil(o.Repositories) {
		return nil, false
	}
	return o.Repositories, true
}

// HasRepositories returns a boolean if a field has been set.
func (o *ProjectSettings) HasRepositories() bool {
	if o != nil && !IsNil(o.Repositories) {
		return true
	}

	return false
}

// SetRepositories gets a reference to the given string and assigns it to the Repositories field.
func (o *ProjectSettings) SetRepositories(v string) {
	o.Repositories = &v
}

func (o ProjectSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["project_id"] = o.ProjectId
	if !IsNil(o.GroupAccess) {
		toSerialize["group_access"] = o.GroupAccess
	}
	if !IsNil(o.RunnerSecrets) {
		toSerialize["runner_secrets"] = o.RunnerSecrets
	}
	if !IsNil(o.Repositories) {
		toSerialize["repositories"] = o.Repositories
	}
	return toSerialize, nil
}

func (o *ProjectSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectSettings := _ProjectSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectSettings)

	if err != nil {
		return err
	}

	*o = ProjectSettings(varProjectSettings)

	return err
}

type NullableProjectSettings struct {
	value *ProjectSettings
	isSet bool
}

func (v NullableProjectSettings) Get() *ProjectSettings {
	return v.value
}

func (v *NullableProjectSettings) Set(val *ProjectSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectSettings(val *ProjectSettings) *NullableProjectSettings {
	return &NullableProjectSettings{value: val, isSet: true}
}

func (v NullableProjectSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
