/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PermissionPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionPatchRequest{}

// PermissionPatchRequest struct for PermissionPatchRequest
type PermissionPatchRequest struct {
	SubjectType *string `json:"subject_type,omitempty"`
	SubjectName *string `json:"subject_name,omitempty"`
	Role        *string `json:"role,omitempty"`
	ProjectId   *string `json:"project_id,omitempty"`
}

// NewPermissionPatchRequest instantiates a new PermissionPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionPatchRequest() *PermissionPatchRequest {
	this := PermissionPatchRequest{}
	return &this
}

// NewPermissionPatchRequestWithDefaults instantiates a new PermissionPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionPatchRequestWithDefaults() *PermissionPatchRequest {
	this := PermissionPatchRequest{}
	return &this
}

// GetSubjectType returns the SubjectType field value if set, zero value otherwise.
func (o *PermissionPatchRequest) GetSubjectType() string {
	if o == nil || IsNil(o.SubjectType) {
		var ret string
		return ret
	}
	return *o.SubjectType
}

// GetSubjectTypeOk returns a tuple with the SubjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionPatchRequest) GetSubjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SubjectType) {
		return nil, false
	}
	return o.SubjectType, true
}

// HasSubjectType returns a boolean if a field has been set.
func (o *PermissionPatchRequest) HasSubjectType() bool {
	if o != nil && !IsNil(o.SubjectType) {
		return true
	}

	return false
}

// SetSubjectType gets a reference to the given string and assigns it to the SubjectType field.
func (o *PermissionPatchRequest) SetSubjectType(v string) {
	o.SubjectType = &v
}

// GetSubjectName returns the SubjectName field value if set, zero value otherwise.
func (o *PermissionPatchRequest) GetSubjectName() string {
	if o == nil || IsNil(o.SubjectName) {
		var ret string
		return ret
	}
	return *o.SubjectName
}

// GetSubjectNameOk returns a tuple with the SubjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionPatchRequest) GetSubjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.SubjectName) {
		return nil, false
	}
	return o.SubjectName, true
}

// HasSubjectName returns a boolean if a field has been set.
func (o *PermissionPatchRequest) HasSubjectName() bool {
	if o != nil && !IsNil(o.SubjectName) {
		return true
	}

	return false
}

// SetSubjectName gets a reference to the given string and assigns it to the SubjectName field.
func (o *PermissionPatchRequest) SetSubjectName(v string) {
	o.SubjectName = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *PermissionPatchRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionPatchRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *PermissionPatchRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *PermissionPatchRequest) SetRole(v string) {
	o.Role = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *PermissionPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *PermissionPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *PermissionPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o PermissionPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubjectType) {
		toSerialize["subject_type"] = o.SubjectType
	}
	if !IsNil(o.SubjectName) {
		toSerialize["subject_name"] = o.SubjectName
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	return toSerialize, nil
}

type NullablePermissionPatchRequest struct {
	value *PermissionPatchRequest
	isSet bool
}

func (v NullablePermissionPatchRequest) Get() *PermissionPatchRequest {
	return v.value
}

func (v *NullablePermissionPatchRequest) Set(val *PermissionPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionPatchRequest(val *PermissionPatchRequest) *NullablePermissionPatchRequest {
	return &NullablePermissionPatchRequest{value: val, isSet: true}
}

func (v NullablePermissionPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
