/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WorkflowSkill type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowSkill{}

// WorkflowSkill struct for WorkflowSkill
type WorkflowSkill struct {
	Id         *string    `json:"id,omitempty"`
	Kind       *string    `json:"kind,omitempty"`
	Href       *string    `json:"href,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
	WorkflowId string     `json:"workflow_id"`
	SkillId    string     `json:"skill_id"`
	Position   int32      `json:"position"`
}

type _WorkflowSkill WorkflowSkill

// NewWorkflowSkill instantiates a new WorkflowSkill object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowSkill(workflowId string, skillId string, position int32) *WorkflowSkill {
	this := WorkflowSkill{}
	this.WorkflowId = workflowId
	this.SkillId = skillId
	this.Position = position
	return &this
}

// NewWorkflowSkillWithDefaults instantiates a new WorkflowSkill object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowSkillWithDefaults() *WorkflowSkill {
	this := WorkflowSkill{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WorkflowSkill) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WorkflowSkill) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WorkflowSkill) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *WorkflowSkill) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *WorkflowSkill) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *WorkflowSkill) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *WorkflowSkill) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *WorkflowSkill) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *WorkflowSkill) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WorkflowSkill) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WorkflowSkill) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WorkflowSkill) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WorkflowSkill) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WorkflowSkill) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *WorkflowSkill) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetWorkflowId returns the WorkflowId field value
func (o *WorkflowSkill) GetWorkflowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *WorkflowSkill) SetWorkflowId(v string) {
	o.WorkflowId = v
}

// GetSkillId returns the SkillId field value
func (o *WorkflowSkill) GetSkillId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SkillId
}

// GetSkillIdOk returns a tuple with the SkillId field value
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetSkillIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkillId, true
}

// SetSkillId sets field value
func (o *WorkflowSkill) SetSkillId(v string) {
	o.SkillId = v
}

// GetPosition returns the Position field value
func (o *WorkflowSkill) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *WorkflowSkill) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *WorkflowSkill) SetPosition(v int32) {
	o.Position = v
}

func (o WorkflowSkill) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowSkill) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["workflow_id"] = o.WorkflowId
	toSerialize["skill_id"] = o.SkillId
	toSerialize["position"] = o.Position
	return toSerialize, nil
}

func (o *WorkflowSkill) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workflow_id",
		"skill_id",
		"position",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowSkill := _WorkflowSkill{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowSkill)

	if err != nil {
		return err
	}

	*o = WorkflowSkill(varWorkflowSkill)

	return err
}

type NullableWorkflowSkill struct {
	value *WorkflowSkill
	isSet bool
}

func (v NullableWorkflowSkill) Get() *WorkflowSkill {
	return v.value
}

func (v *NullableWorkflowSkill) Set(val *WorkflowSkill) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowSkill) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowSkill) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowSkill(val *WorkflowSkill) *NullableWorkflowSkill {
	return &NullableWorkflowSkill{value: val, isSet: true}
}

func (v NullableWorkflowSkill) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowSkill) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
