/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowTaskPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowTaskPatchRequest{}

// WorkflowTaskPatchRequest struct for WorkflowTaskPatchRequest
type WorkflowTaskPatchRequest struct {
	WorkflowId *string `json:"workflow_id,omitempty"`
	TaskId     *string `json:"task_id,omitempty"`
	Position   *int32  `json:"position,omitempty"`
}

// NewWorkflowTaskPatchRequest instantiates a new WorkflowTaskPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowTaskPatchRequest() *WorkflowTaskPatchRequest {
	this := WorkflowTaskPatchRequest{}
	return &this
}

// NewWorkflowTaskPatchRequestWithDefaults instantiates a new WorkflowTaskPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowTaskPatchRequestWithDefaults() *WorkflowTaskPatchRequest {
	this := WorkflowTaskPatchRequest{}
	return &this
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *WorkflowTaskPatchRequest) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskPatchRequest) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *WorkflowTaskPatchRequest) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *WorkflowTaskPatchRequest) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *WorkflowTaskPatchRequest) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskPatchRequest) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *WorkflowTaskPatchRequest) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *WorkflowTaskPatchRequest) SetTaskId(v string) {
	o.TaskId = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *WorkflowTaskPatchRequest) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskPatchRequest) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *WorkflowTaskPatchRequest) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *WorkflowTaskPatchRequest) SetPosition(v int32) {
	o.Position = &v
}

func (o WorkflowTaskPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowTaskPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.TaskId) {
		toSerialize["task_id"] = o.TaskId
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableWorkflowTaskPatchRequest struct {
	value *WorkflowTaskPatchRequest
	isSet bool
}

func (v NullableWorkflowTaskPatchRequest) Get() *WorkflowTaskPatchRequest {
	return v.value
}

func (v *NullableWorkflowTaskPatchRequest) Set(val *WorkflowTaskPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowTaskPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowTaskPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowTaskPatchRequest(val *WorkflowTaskPatchRequest) *NullableWorkflowTaskPatchRequest {
	return &NullableWorkflowTaskPatchRequest{value: val, isSet: true}
}

func (v NullableWorkflowTaskPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowTaskPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
