/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowSkillPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowSkillPatchRequest{}

// WorkflowSkillPatchRequest struct for WorkflowSkillPatchRequest
type WorkflowSkillPatchRequest struct {
	WorkflowId *string `json:"workflow_id,omitempty"`
	SkillId    *string `json:"skill_id,omitempty"`
	Position   *int32  `json:"position,omitempty"`
}

// NewWorkflowSkillPatchRequest instantiates a new WorkflowSkillPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowSkillPatchRequest() *WorkflowSkillPatchRequest {
	this := WorkflowSkillPatchRequest{}
	return &this
}

// NewWorkflowSkillPatchRequestWithDefaults instantiates a new WorkflowSkillPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowSkillPatchRequestWithDefaults() *WorkflowSkillPatchRequest {
	this := WorkflowSkillPatchRequest{}
	return &this
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *WorkflowSkillPatchRequest) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkillPatchRequest) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *WorkflowSkillPatchRequest) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *WorkflowSkillPatchRequest) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetSkillId returns the SkillId field value if set, zero value otherwise.
func (o *WorkflowSkillPatchRequest) GetSkillId() string {
	if o == nil || IsNil(o.SkillId) {
		var ret string
		return ret
	}
	return *o.SkillId
}

// GetSkillIdOk returns a tuple with the SkillId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkillPatchRequest) GetSkillIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkillId) {
		return nil, false
	}
	return o.SkillId, true
}

// HasSkillId returns a boolean if a field has been set.
func (o *WorkflowSkillPatchRequest) HasSkillId() bool {
	if o != nil && !IsNil(o.SkillId) {
		return true
	}

	return false
}

// SetSkillId gets a reference to the given string and assigns it to the SkillId field.
func (o *WorkflowSkillPatchRequest) SetSkillId(v string) {
	o.SkillId = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *WorkflowSkillPatchRequest) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSkillPatchRequest) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *WorkflowSkillPatchRequest) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *WorkflowSkillPatchRequest) SetPosition(v int32) {
	o.Position = &v
}

func (o WorkflowSkillPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowSkillPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.SkillId) {
		toSerialize["skill_id"] = o.SkillId
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableWorkflowSkillPatchRequest struct {
	value *WorkflowSkillPatchRequest
	isSet bool
}

func (v NullableWorkflowSkillPatchRequest) Get() *WorkflowSkillPatchRequest {
	return v.value
}

func (v *NullableWorkflowSkillPatchRequest) Set(val *WorkflowSkillPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowSkillPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowSkillPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowSkillPatchRequest(val *WorkflowSkillPatchRequest) *NullableWorkflowSkillPatchRequest {
	return &NullableWorkflowSkillPatchRequest{value: val, isSet: true}
}

func (v NullableWorkflowSkillPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowSkillPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
