/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPatchRequest{}

// UserPatchRequest struct for UserPatchRequest
type UserPatchRequest struct {
	Username *string `json:"username,omitempty"`
	Name     *string `json:"name,omitempty"`
	Groups   *string `json:"groups,omitempty"`
}

// NewUserPatchRequest instantiates a new UserPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPatchRequest() *UserPatchRequest {
	this := UserPatchRequest{}
	return &this
}

// NewUserPatchRequestWithDefaults instantiates a new UserPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPatchRequestWithDefaults() *UserPatchRequest {
	this := UserPatchRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UserPatchRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPatchRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UserPatchRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UserPatchRequest) SetUsername(v string) {
	o.Username = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *UserPatchRequest) GetGroups() string {
	if o == nil || IsNil(o.Groups) {
		var ret string
		return ret
	}
	return *o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPatchRequest) GetGroupsOk() (*string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *UserPatchRequest) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given string and assigns it to the Groups field.
func (o *UserPatchRequest) SetGroups(v string) {
	o.Groups = &v
}

func (o UserPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	return toSerialize, nil
}

type NullableUserPatchRequest struct {
	value *UserPatchRequest
	isSet bool
}

func (v NullableUserPatchRequest) Get() *UserPatchRequest {
	return v.value
}

func (v *NullableUserPatchRequest) Set(val *UserPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPatchRequest(val *UserPatchRequest) *NullableUserPatchRequest {
	return &NullableUserPatchRequest{value: val, isSet: true}
}

func (v NullableUserPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
