/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectSettingsPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectSettingsPatchRequest{}

// ProjectSettingsPatchRequest struct for ProjectSettingsPatchRequest
type ProjectSettingsPatchRequest struct {
	ProjectId     *string `json:"project_id,omitempty"`
	GroupAccess   *string `json:"group_access,omitempty"`
	RunnerSecrets *string `json:"runner_secrets,omitempty"`
	Repositories  *string `json:"repositories,omitempty"`
}

// NewProjectSettingsPatchRequest instantiates a new ProjectSettingsPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectSettingsPatchRequest() *ProjectSettingsPatchRequest {
	this := ProjectSettingsPatchRequest{}
	return &this
}

// NewProjectSettingsPatchRequestWithDefaults instantiates a new ProjectSettingsPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectSettingsPatchRequestWithDefaults() *ProjectSettingsPatchRequest {
	this := ProjectSettingsPatchRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ProjectSettingsPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectSettingsPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ProjectSettingsPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetGroupAccess returns the GroupAccess field value if set, zero value otherwise.
func (o *ProjectSettingsPatchRequest) GetGroupAccess() string {
	if o == nil || IsNil(o.GroupAccess) {
		var ret string
		return ret
	}
	return *o.GroupAccess
}

// GetGroupAccessOk returns a tuple with the GroupAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequest) GetGroupAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GroupAccess) {
		return nil, false
	}
	return o.GroupAccess, true
}

// HasGroupAccess returns a boolean if a field has been set.
func (o *ProjectSettingsPatchRequest) HasGroupAccess() bool {
	if o != nil && !IsNil(o.GroupAccess) {
		return true
	}

	return false
}

// SetGroupAccess gets a reference to the given string and assigns it to the GroupAccess field.
func (o *ProjectSettingsPatchRequest) SetGroupAccess(v string) {
	o.GroupAccess = &v
}

// GetRunnerSecrets returns the RunnerSecrets field value if set, zero value otherwise.
func (o *ProjectSettingsPatchRequest) GetRunnerSecrets() string {
	if o == nil || IsNil(o.RunnerSecrets) {
		var ret string
		return ret
	}
	return *o.RunnerSecrets
}

// GetRunnerSecretsOk returns a tuple with the RunnerSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequest) GetRunnerSecretsOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerSecrets) {
		return nil, false
	}
	return o.RunnerSecrets, true
}

// HasRunnerSecrets returns a boolean if a field has been set.
func (o *ProjectSettingsPatchRequest) HasRunnerSecrets() bool {
	if o != nil && !IsNil(o.RunnerSecrets) {
		return true
	}

	return false
}

// SetRunnerSecrets gets a reference to the given string and assigns it to the RunnerSecrets field.
func (o *ProjectSettingsPatchRequest) SetRunnerSecrets(v string) {
	o.RunnerSecrets = &v
}

// GetRepositories returns the Repositories field value if set, zero value otherwise.
func (o *ProjectSettingsPatchRequest) GetRepositories() string {
	if o == nil || IsNil(o.Repositories) {
		var ret string
		return ret
	}
	return *o.Repositories
}

// GetRepositoriesOk returns a tuple with the Repositories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequest) GetRepositoriesOk() (*string, bool) {
	if o == nil || IsNil(o.Repositories) {
		return nil, false
	}
	return o.Repositories, true
}

// HasRepositories returns a boolean if a field has been set.
func (o *ProjectSettingsPatchRequest) HasRepositories() bool {
	if o != nil && !IsNil(o.Repositories) {
		return true
	}

	return false
}

// SetRepositories gets a reference to the given string and assigns it to the Repositories field.
func (o *ProjectSettingsPatchRequest) SetRepositories(v string) {
	o.Repositories = &v
}

func (o ProjectSettingsPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectSettingsPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.GroupAccess) {
		toSerialize["group_access"] = o.GroupAccess
	}
	if !IsNil(o.RunnerSecrets) {
		toSerialize["runner_secrets"] = o.RunnerSecrets
	}
	if !IsNil(o.Repositories) {
		toSerialize["repositories"] = o.Repositories
	}
	return toSerialize, nil
}

type NullableProjectSettingsPatchRequest struct {
	value *ProjectSettingsPatchRequest
	isSet bool
}

func (v NullableProjectSettingsPatchRequest) Get() *ProjectSettingsPatchRequest {
	return v.value
}

func (v *NullableProjectSettingsPatchRequest) Set(val *ProjectSettingsPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectSettingsPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectSettingsPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectSettingsPatchRequest(val *ProjectSettingsPatchRequest) *NullableProjectSettingsPatchRequest {
	return &NullableProjectSettingsPatchRequest{value: val, isSet: true}
}

func (v NullableProjectSettingsPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectSettingsPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
