/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProjectKeyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectKeyList{}

// ProjectKeyList struct for ProjectKeyList
type ProjectKeyList struct {
	Kind  string       `json:"kind"`
	Page  int32        `json:"page"`
	Size  int32        `json:"size"`
	Total int32        `json:"total"`
	Items []ProjectKey `json:"items"`
}

type _ProjectKeyList ProjectKeyList

// NewProjectKeyList instantiates a new ProjectKeyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectKeyList(kind string, page int32, size int32, total int32, items []ProjectKey) *ProjectKeyList {
	this := ProjectKeyList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewProjectKeyListWithDefaults instantiates a new ProjectKeyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectKeyListWithDefaults() *ProjectKeyList {
	this := ProjectKeyList{}
	return &this
}

// GetKind returns the Kind field value
func (o *ProjectKeyList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ProjectKeyList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ProjectKeyList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *ProjectKeyList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ProjectKeyList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ProjectKeyList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ProjectKeyList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ProjectKeyList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ProjectKeyList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ProjectKeyList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ProjectKeyList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ProjectKeyList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *ProjectKeyList) GetItems() []ProjectKey {
	if o == nil {
		var ret []ProjectKey
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ProjectKeyList) GetItemsOk() ([]ProjectKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ProjectKeyList) SetItems(v []ProjectKey) {
	o.Items = v
}

func (o ProjectKeyList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectKeyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ProjectKeyList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectKeyList := _ProjectKeyList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectKeyList)

	if err != nil {
		return err
	}

	*o = ProjectKeyList(varProjectKeyList)

	return err
}

type NullableProjectKeyList struct {
	value *ProjectKeyList
	isSet bool
}

func (v NullableProjectKeyList) Get() *ProjectKeyList {
	return v.value
}

func (v *NullableProjectKeyList) Set(val *ProjectKeyList) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectKeyList) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectKeyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectKeyList(val *ProjectKeyList) *NullableProjectKeyList {
	return &NullableProjectKeyList{value: val, isSet: true}
}

func (v NullableProjectKeyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectKeyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
