/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowPatchRequest{}

// WorkflowPatchRequest struct for WorkflowPatchRequest
type WorkflowPatchRequest struct {
	Name      *string `json:"name,omitempty"`
	RepoUrl   *string `json:"repo_url,omitempty"`
	Prompt    *string `json:"prompt,omitempty"`
	AgentId   *string `json:"agent_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	Branch    *string `json:"branch,omitempty"`
	Path      *string `json:"path,omitempty"`
}

// NewWorkflowPatchRequest instantiates a new WorkflowPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowPatchRequest() *WorkflowPatchRequest {
	this := WorkflowPatchRequest{}
	return &this
}

// NewWorkflowPatchRequestWithDefaults instantiates a new WorkflowPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowPatchRequestWithDefaults() *WorkflowPatchRequest {
	this := WorkflowPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WorkflowPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *WorkflowPatchRequest) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *WorkflowPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *WorkflowPatchRequest) SetAgentId(v string) {
	o.AgentId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *WorkflowPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *WorkflowPatchRequest) SetBranch(v string) {
	o.Branch = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *WorkflowPatchRequest) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowPatchRequest) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *WorkflowPatchRequest) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *WorkflowPatchRequest) SetPath(v string) {
	o.Path = &v
}

func (o WorkflowPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.AgentId) {
		toSerialize["agent_id"] = o.AgentId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

type NullableWorkflowPatchRequest struct {
	value *WorkflowPatchRequest
	isSet bool
}

func (v NullableWorkflowPatchRequest) Get() *WorkflowPatchRequest {
	return v.value
}

func (v *NullableWorkflowPatchRequest) Set(val *WorkflowPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowPatchRequest(val *WorkflowPatchRequest) *NullableWorkflowPatchRequest {
	return &NullableWorkflowPatchRequest{value: val, isSet: true}
}

func (v NullableWorkflowPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
