/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TaskPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskPatchRequest{}

// TaskPatchRequest struct for TaskPatchRequest
type TaskPatchRequest struct {
	Name      *string `json:"name,omitempty"`
	RepoUrl   *string `json:"repo_url,omitempty"`
	Prompt    *string `json:"prompt,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
}

// NewTaskPatchRequest instantiates a new TaskPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskPatchRequest() *TaskPatchRequest {
	this := TaskPatchRequest{}
	return &this
}

// NewTaskPatchRequestWithDefaults instantiates a new TaskPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskPatchRequestWithDefaults() *TaskPatchRequest {
	this := TaskPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TaskPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TaskPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TaskPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *TaskPatchRequest) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskPatchRequest) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *TaskPatchRequest) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *TaskPatchRequest) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *TaskPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *TaskPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *TaskPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *TaskPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *TaskPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *TaskPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o TaskPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	return toSerialize, nil
}

type NullableTaskPatchRequest struct {
	value *TaskPatchRequest
	isSet bool
}

func (v NullableTaskPatchRequest) Get() *TaskPatchRequest {
	return v.value
}

func (v *NullableTaskPatchRequest) Set(val *TaskPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskPatchRequest(val *TaskPatchRequest) *NullableTaskPatchRequest {
	return &NullableTaskPatchRequest{value: val, isSet: true}
}

func (v NullableTaskPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
