/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RepositoryRefPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryRefPatchRequest{}

// RepositoryRefPatchRequest struct for RepositoryRefPatchRequest
type RepositoryRefPatchRequest struct {
	Name      *string `json:"name,omitempty"`
	Url       *string `json:"url,omitempty"`
	Branch    *string `json:"branch,omitempty"`
	Provider  *string `json:"provider,omitempty"`
	Owner     *string `json:"owner,omitempty"`
	RepoName  *string `json:"repo_name,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
}

// NewRepositoryRefPatchRequest instantiates a new RepositoryRefPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryRefPatchRequest() *RepositoryRefPatchRequest {
	this := RepositoryRefPatchRequest{}
	return &this
}

// NewRepositoryRefPatchRequestWithDefaults instantiates a new RepositoryRefPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryRefPatchRequestWithDefaults() *RepositoryRefPatchRequest {
	this := RepositoryRefPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RepositoryRefPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *RepositoryRefPatchRequest) SetUrl(v string) {
	o.Url = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *RepositoryRefPatchRequest) SetBranch(v string) {
	o.Branch = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *RepositoryRefPatchRequest) SetProvider(v string) {
	o.Provider = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *RepositoryRefPatchRequest) SetOwner(v string) {
	o.Owner = &v
}

// GetRepoName returns the RepoName field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetRepoName() string {
	if o == nil || IsNil(o.RepoName) {
		var ret string
		return ret
	}
	return *o.RepoName
}

// GetRepoNameOk returns a tuple with the RepoName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetRepoNameOk() (*string, bool) {
	if o == nil || IsNil(o.RepoName) {
		return nil, false
	}
	return o.RepoName, true
}

// HasRepoName returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasRepoName() bool {
	if o != nil && !IsNil(o.RepoName) {
		return true
	}

	return false
}

// SetRepoName gets a reference to the given string and assigns it to the RepoName field.
func (o *RepositoryRefPatchRequest) SetRepoName(v string) {
	o.RepoName = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *RepositoryRefPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryRefPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *RepositoryRefPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *RepositoryRefPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o RepositoryRefPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryRefPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.RepoName) {
		toSerialize["repo_name"] = o.RepoName
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	return toSerialize, nil
}

type NullableRepositoryRefPatchRequest struct {
	value *RepositoryRefPatchRequest
	isSet bool
}

func (v NullableRepositoryRefPatchRequest) Get() *RepositoryRefPatchRequest {
	return v.value
}

func (v *NullableRepositoryRefPatchRequest) Set(val *RepositoryRefPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryRefPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryRefPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryRefPatchRequest(val *RepositoryRefPatchRequest) *NullableRepositoryRefPatchRequest {
	return &NullableRepositoryRefPatchRequest{value: val, isSet: true}
}

func (v NullableRepositoryRefPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryRefPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
