/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: admin@your.project.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectKeyPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectKeyPatchRequest{}

// ProjectKeyPatchRequest struct for ProjectKeyPatchRequest
type ProjectKeyPatchRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewProjectKeyPatchRequest instantiates a new ProjectKeyPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectKeyPatchRequest() *ProjectKeyPatchRequest {
	this := ProjectKeyPatchRequest{}
	return &this
}

// NewProjectKeyPatchRequestWithDefaults instantiates a new ProjectKeyPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectKeyPatchRequestWithDefaults() *ProjectKeyPatchRequest {
	this := ProjectKeyPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectKeyPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectKeyPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectKeyPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectKeyPatchRequest) SetName(v string) {
	o.Name = &v
}

func (o ProjectKeyPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectKeyPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableProjectKeyPatchRequest struct {
	value *ProjectKeyPatchRequest
	isSet bool
}

func (v NullableProjectKeyPatchRequest) Get() *ProjectKeyPatchRequest {
	return v.value
}

func (v *NullableProjectKeyPatchRequest) Set(val *ProjectKeyPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectKeyPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectKeyPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectKeyPatchRequest(val *ProjectKeyPatchRequest) *NullableProjectKeyPatchRequest {
	return &NullableProjectKeyPatchRequest{value: val, isSet: true}
}

func (v NullableProjectKeyPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectKeyPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
