// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f729ebc11ad1c453eeb0a679fa5c14eb1bc0096450cd18ca79e7c9b7b5c81acf
// Generated: 2026-03-05T04:28:57Z

import type { AmbientClientConfig } from './base';
import { ProjectAPI } from './project_api';
import { ProjectSettingsAPI } from './project_settings_api';
import { SessionAPI } from './session_api';
import { UserAPI } from './user_api';


export class AmbientClient {
  private readonly config: AmbientClientConfig;

  readonly projects: ProjectAPI;
  readonly projectSettings: ProjectSettingsAPI;
  readonly sessions: SessionAPI;
  readonly users: UserAPI;

  constructor(config: AmbientClientConfig) {
    if (!config.baseUrl) {
      throw new Error('baseUrl is required');
    }
    if (!config.token) {
      throw new Error('token is required');
    }
    if (config.token.length < 20) {
      throw new Error('token is too short (minimum 20 characters)');
    }
    if (config.token === 'YOUR_TOKEN_HERE' || config.token === 'PLACEHOLDER_TOKEN') {
      throw new Error('placeholder token is not allowed');
    }
    if (!config.project) {
      throw new Error('project is required');
    }
    if (config.project.length > 63) {
      throw new Error('project name cannot exceed 63 characters');
    }

    const url = new URL(config.baseUrl);
    if (url.protocol !== 'http:' && url.protocol !== 'https:') {
      throw new Error('only HTTP and HTTPS schemes are supported');
    }

    this.config = {
      ...config,
      baseUrl: config.baseUrl.replace(/\/+$/, ''),
    };

    this.projects = new ProjectAPI(this.config);
    this.projectSettings = new ProjectSettingsAPI(this.config);
    this.sessions = new SessionAPI(this.config);
    this.users = new UserAPI(this.config);
  }

  static fromEnv(): AmbientClient {
    const baseUrl = process.env.AMBIENT_API_URL || 'http://localhost:8080';
    const token = process.env.AMBIENT_TOKEN;
    const project = process.env.AMBIENT_PROJECT;

    if (!token) {
      throw new Error('AMBIENT_TOKEN environment variable is required');
    }
    if (!project) {
      throw new Error('AMBIENT_PROJECT environment variable is required');
    }

    return new AmbientClient({ baseUrl, token, project });
  }
}
