// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { AmbientClientConfig } from './base';
import { AgentAPI } from './agent_api';
import { PermissionAPI } from './permission_api';
import { ProjectAPI } from './project_api';
import { ProjectKeyAPI } from './project_key_api';
import { ProjectSettingsAPI } from './project_settings_api';
import { RepositoryRefAPI } from './repository_ref_api';
import { SessionAPI } from './session_api';
import { SkillAPI } from './skill_api';
import { TaskAPI } from './task_api';
import { UserAPI } from './user_api';
import { WorkflowAPI } from './workflow_api';
import { WorkflowSkillAPI } from './workflow_skill_api';
import { WorkflowTaskAPI } from './workflow_task_api';


export class AmbientClient {
  private readonly config: AmbientClientConfig;

  readonly agents: AgentAPI;
  readonly permissions: PermissionAPI;
  readonly projects: ProjectAPI;
  readonly projectKeys: ProjectKeyAPI;
  readonly projectSettings: ProjectSettingsAPI;
  readonly repositoryRefs: RepositoryRefAPI;
  readonly sessions: SessionAPI;
  readonly skills: SkillAPI;
  readonly tasks: TaskAPI;
  readonly users: UserAPI;
  readonly workflows: WorkflowAPI;
  readonly workflowSkills: WorkflowSkillAPI;
  readonly workflowTasks: WorkflowTaskAPI;

  constructor(config: AmbientClientConfig) {
    if (!config.baseUrl) {
      throw new Error('baseUrl is required');
    }
    if (!config.token) {
      throw new Error('token is required');
    }
    if (!config.project) {
      throw new Error('project is required');
    }

    this.config = {
      ...config,
      baseUrl: config.baseUrl.replace(/\/+$/, ''),
    };

    this.agents = new AgentAPI(this.config);
    this.permissions = new PermissionAPI(this.config);
    this.projects = new ProjectAPI(this.config);
    this.projectKeys = new ProjectKeyAPI(this.config);
    this.projectSettings = new ProjectSettingsAPI(this.config);
    this.repositoryRefs = new RepositoryRefAPI(this.config);
    this.sessions = new SessionAPI(this.config);
    this.skills = new SkillAPI(this.config);
    this.tasks = new TaskAPI(this.config);
    this.users = new UserAPI(this.config);
    this.workflows = new WorkflowAPI(this.config);
    this.workflowSkills = new WorkflowSkillAPI(this.config);
    this.workflowTasks = new WorkflowTaskAPI(this.config);
  }

  static fromEnv(): AmbientClient {
    const baseUrl = process.env.AMBIENT_API_URL || 'http://localhost:8080';
    const token = process.env.AMBIENT_TOKEN;
    const project = process.env.AMBIENT_PROJECT;

    if (!token) {
      throw new Error('AMBIENT_TOKEN environment variable is required');
    }
    if (!project) {
      throw new Error('AMBIENT_PROJECT environment variable is required');
    }

    return new AmbientClient({ baseUrl, token, project });
  }
}
