// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type Permission = ObjectReference & {
  project_id: string;
  role: string;
  subject_name: string;
  subject_type: string;
};

export type PermissionList = ListMeta & {
  items: Permission[];
};

export type PermissionCreateRequest = {
  project_id?: string;
  role: string;
  subject_name: string;
  subject_type: string;
};

export type PermissionPatchRequest = {
  project_id?: string;
  role?: string;
  subject_name?: string;
  subject_type?: string;
};

export class PermissionBuilder {
  private data: Record<string, unknown> = {};


  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  role(value: string): this {
    this.data['role'] = value;
    return this;
  }

  subjectName(value: string): this {
    this.data['subject_name'] = value;
    return this;
  }

  subjectType(value: string): this {
    this.data['subject_type'] = value;
    return this;
  }

  build(): PermissionCreateRequest {
    if (!this.data['role']) {
      throw new Error('role is required');
    }
    if (!this.data['subject_name']) {
      throw new Error('subject_name is required');
    }
    if (!this.data['subject_type']) {
      throw new Error('subject_type is required');
    }
    return this.data as PermissionCreateRequest;
  }
}

export class PermissionPatchBuilder {
  private data: Record<string, unknown> = {};


  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  role(value: string): this {
    this.data['role'] = value;
    return this;
  }

  subjectName(value: string): this {
    this.data['subject_name'] = value;
    return this;
  }

  subjectType(value: string): this {
    this.data['subject_type'] = value;
    return this;
  }

  build(): PermissionPatchRequest {
    return this.data as PermissionPatchRequest;
  }
}

