// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f729ebc11ad1c453eeb0a679fa5c14eb1bc0096450cd18ca79e7c9b7b5c81acf
// Generated: 2026-03-05T04:28:57Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { ProjectSettings, ProjectSettingsList, ProjectSettingsCreateRequest, ProjectSettingsPatchRequest } from './project_settings';

export class ProjectSettingsAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: ProjectSettingsCreateRequest, opts?: RequestOptions): Promise<ProjectSettings> {
    return ambientFetch<ProjectSettings>(this.config, 'POST', '/project_settings', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ProjectSettings> {
    return ambientFetch<ProjectSettings>(this.config, 'GET', `/project_settings/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ProjectSettingsList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ProjectSettingsList>(this.config, 'GET', `/project_settings${qs}`, undefined, opts);
  }
  async update(id: string, patch: ProjectSettingsPatchRequest, opts?: RequestOptions): Promise<ProjectSettings> {
    return ambientFetch<ProjectSettings>(this.config, 'PATCH', `/project_settings/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/project_settings/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ProjectSettings> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
