// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectSettings = ObjectReference & {
  group_access: string;
  project_id: string;
  repositories: string;
  runner_secrets: string;
};

export type ProjectSettingsList = ListMeta & {
  items: ProjectSettings[];
};

export type ProjectSettingsCreateRequest = {
  group_access?: string;
  project_id: string;
  repositories?: string;
  runner_secrets?: string;
};

export type ProjectSettingsPatchRequest = {
  group_access?: string;
  project_id?: string;
  repositories?: string;
  runner_secrets?: string;
};

export class ProjectSettingsBuilder {
  private data: Record<string, unknown> = {};


  groupAccess(value: string): this {
    this.data['group_access'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  repositories(value: string): this {
    this.data['repositories'] = value;
    return this;
  }

  runnerSecrets(value: string): this {
    this.data['runner_secrets'] = value;
    return this;
  }

  build(): ProjectSettingsCreateRequest {
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as ProjectSettingsCreateRequest;
  }
}

export class ProjectSettingsPatchBuilder {
  private data: Record<string, unknown> = {};


  groupAccess(value: string): this {
    this.data['group_access'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  repositories(value: string): this {
    this.data['repositories'] = value;
    return this;
  }

  runnerSecrets(value: string): this {
    this.data['runner_secrets'] = value;
    return this;
  }

  build(): ProjectSettingsPatchRequest {
    return this.data as ProjectSettingsPatchRequest;
  }
}

