// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type Project = ObjectReference & {
  annotations: string;
  description: string;
  display_name: string;
  labels: string;
  name: string;
  status: string;
};

export type ProjectList = ListMeta & {
  items: Project[];
};

export type ProjectCreateRequest = {
  annotations?: string;
  description?: string;
  display_name?: string;
  labels?: string;
  name: string;
  status?: string;
};

export type ProjectPatchRequest = {
  annotations?: string;
  description?: string;
  display_name?: string;
  labels?: string;
  name?: string;
  status?: string;
};

export class ProjectBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ProjectCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as ProjectCreateRequest;
  }
}

export class ProjectPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ProjectPatchRequest {
    return this.data as ProjectPatchRequest;
  }
}

