// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectKey = ObjectReference & {
  expires_at: string;
  key_prefix: string;
  last_used_at: string;
  name: string;
  plaintext_key: string;
  project_id: string;
};

export type ProjectKeyList = ListMeta & {
  items: ProjectKey[];
};

export type ProjectKeyCreateRequest = {
  expires_at?: string;
  key_prefix?: string;
  last_used_at?: string;
  name: string;
  plaintext_key?: string;
  project_id?: string;
};

export type ProjectKeyPatchRequest = {
  name?: string;
};

export class ProjectKeyBuilder {
  private data: Record<string, unknown> = {};


  expiresAt(value: string): this {
    this.data['expires_at'] = value;
    return this;
  }

  keyPrefix(value: string): this {
    this.data['key_prefix'] = value;
    return this;
  }

  lastUsedAt(value: string): this {
    this.data['last_used_at'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  plaintextKey(value: string): this {
    this.data['plaintext_key'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  build(): ProjectKeyCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as ProjectKeyCreateRequest;
  }
}

export class ProjectKeyPatchBuilder {
  private data: Record<string, unknown> = {};


  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  build(): ProjectKeyPatchRequest {
    return this.data as ProjectKeyPatchRequest;
  }
}

