// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type RepositoryRef = ObjectReference & {
  branch: string;
  name: string;
  owner: string;
  project_id: string;
  provider: string;
  repo_name: string;
  url: string;
};

export type RepositoryRefList = ListMeta & {
  items: RepositoryRef[];
};

export type RepositoryRefCreateRequest = {
  branch?: string;
  name: string;
  owner?: string;
  project_id?: string;
  provider?: string;
  repo_name?: string;
  url: string;
};

export type RepositoryRefPatchRequest = {
  branch?: string;
  name?: string;
  owner?: string;
  project_id?: string;
  provider?: string;
  repo_name?: string;
  url?: string;
};

export class RepositoryRefBuilder {
  private data: Record<string, unknown> = {};


  branch(value: string): this {
    this.data['branch'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  owner(value: string): this {
    this.data['owner'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  repoName(value: string): this {
    this.data['repo_name'] = value;
    return this;
  }

  url(value: string): this {
    this.data['url'] = value;
    return this;
  }

  build(): RepositoryRefCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['url']) {
      throw new Error('url is required');
    }
    return this.data as RepositoryRefCreateRequest;
  }
}

export class RepositoryRefPatchBuilder {
  private data: Record<string, unknown> = {};


  branch(value: string): this {
    this.data['branch'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  owner(value: string): this {
    this.data['owner'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  repoName(value: string): this {
    this.data['repo_name'] = value;
    return this;
  }

  url(value: string): this {
    this.data['url'] = value;
    return this;
  }

  build(): RepositoryRefPatchRequest {
    return this.data as RepositoryRefPatchRequest;
  }
}

