// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type Skill = ObjectReference & {
  name: string;
  project_id: string;
  prompt: string;
  repo_url: string;
};

export type SkillList = ListMeta & {
  items: Skill[];
};

export type SkillCreateRequest = {
  name: string;
  project_id?: string;
  prompt?: string;
  repo_url?: string;
};

export type SkillPatchRequest = {
  name?: string;
  project_id?: string;
  prompt?: string;
  repo_url?: string;
};

export class SkillBuilder {
  private data: Record<string, unknown> = {};


  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  repoUrl(value: string): this {
    this.data['repo_url'] = value;
    return this;
  }

  build(): SkillCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as SkillCreateRequest;
  }
}

export class SkillPatchBuilder {
  private data: Record<string, unknown> = {};


  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  repoUrl(value: string): this {
    this.data['repo_url'] = value;
    return this;
  }

  build(): SkillPatchRequest {
    return this.data as SkillPatchRequest;
  }
}

