// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { User, UserList, UserCreateRequest, UserPatchRequest } from './user';

export class UserAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: UserCreateRequest, opts?: RequestOptions): Promise<User> {
    return ambientFetch<User>(this.config, 'POST', '/users', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<User> {
    return ambientFetch<User>(this.config, 'GET', `/users/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<UserList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<UserList>(this.config, 'GET', `/users${qs}`, undefined, opts);
  }
  async update(id: string, patch: UserPatchRequest, opts?: RequestOptions): Promise<User> {
    return ambientFetch<User>(this.config, 'PATCH', `/users/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/users/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<User> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
