// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type User = ObjectReference & {
  groups: string;
  name: string;
  username: string;
};

export type UserList = ListMeta & {
  items: User[];
};

export type UserCreateRequest = {
  groups?: string;
  name: string;
  username: string;
};

export type UserPatchRequest = {
  groups?: string;
  name?: string;
  username?: string;
};

export class UserBuilder {
  private data: Record<string, unknown> = {};


  groups(value: string): this {
    this.data['groups'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['username']) {
      throw new Error('username is required');
    }
    return this.data as UserCreateRequest;
  }
}

export class UserPatchBuilder {
  private data: Record<string, unknown> = {};


  groups(value: string): this {
    this.data['groups'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserPatchRequest {
    return this.data as UserPatchRequest;
  }
}

