// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { WorkflowTask, WorkflowTaskList, WorkflowTaskCreateRequest, WorkflowTaskPatchRequest } from './workflow_task';

export class WorkflowTaskAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: WorkflowTaskCreateRequest, opts?: RequestOptions): Promise<WorkflowTask> {
    return ambientFetch<WorkflowTask>(this.config, 'POST', '/workflow_tasks', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<WorkflowTask> {
    return ambientFetch<WorkflowTask>(this.config, 'GET', `/workflow_tasks/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<WorkflowTaskList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<WorkflowTaskList>(this.config, 'GET', `/workflow_tasks${qs}`, undefined, opts);
  }
  async update(id: string, patch: WorkflowTaskPatchRequest, opts?: RequestOptions): Promise<WorkflowTask> {
    return ambientFetch<WorkflowTask>(this.config, 'PATCH', `/workflow_tasks/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<WorkflowTask> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
