// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { ObjectReference, ListMeta } from './base';

export type WorkflowTask = ObjectReference & {
  position: number;
  task_id: string;
  workflow_id: string;
};

export type WorkflowTaskList = ListMeta & {
  items: WorkflowTask[];
};

export type WorkflowTaskCreateRequest = {
  position: number;
  task_id: string;
  workflow_id: string;
};

export type WorkflowTaskPatchRequest = {
  position?: number;
  task_id?: string;
  workflow_id?: string;
};

export class WorkflowTaskBuilder {
  private data: Record<string, unknown> = {};


  position(value: number): this {
    this.data['position'] = value;
    return this;
  }

  taskId(value: string): this {
    this.data['task_id'] = value;
    return this;
  }

  workflowId(value: string): this {
    this.data['workflow_id'] = value;
    return this;
  }

  build(): WorkflowTaskCreateRequest {
    if (!this.data['task_id']) {
      throw new Error('task_id is required');
    }
    if (!this.data['workflow_id']) {
      throw new Error('workflow_id is required');
    }
    return this.data as WorkflowTaskCreateRequest;
  }
}

export class WorkflowTaskPatchBuilder {
  private data: Record<string, unknown> = {};


  position(value: number): this {
    this.data['position'] = value;
    return this;
  }

  taskId(value: string): this {
    this.data['task_id'] = value;
    return this;
  }

  workflowId(value: string): this {
    this.data['workflow_id'] = value;
    return this;
  }

  build(): WorkflowTaskPatchRequest {
    return this.data as WorkflowTaskPatchRequest;
  }
}

