// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Workflow, WorkflowList, WorkflowCreateRequest, WorkflowPatchRequest } from './workflow';

export class WorkflowAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: WorkflowCreateRequest, opts?: RequestOptions): Promise<Workflow> {
    return ambientFetch<Workflow>(this.config, 'POST', '/workflows', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Workflow> {
    return ambientFetch<Workflow>(this.config, 'GET', `/workflows/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<WorkflowList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<WorkflowList>(this.config, 'GET', `/workflows${qs}`, undefined, opts);
  }
  async update(id: string, patch: WorkflowPatchRequest, opts?: RequestOptions): Promise<Workflow> {
    return ambientFetch<Workflow>(this.config, 'PATCH', `/workflows/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Workflow> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
