# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .repository_ref import RepositoryRef, RepositoryRefList

if TYPE_CHECKING:
    from .client import AmbientClient


class RepositoryRefAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> RepositoryRef:
        resp = self._client._request("POST", "/repository_refs", json=data)
        return RepositoryRef.from_dict(resp)

    def get(self, resource_id: str) -> RepositoryRef:
        resp = self._client._request("GET", f"/repository_refs/{resource_id}")
        return RepositoryRef.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> RepositoryRefList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/repository_refs", params=params)
        return RepositoryRefList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> RepositoryRef:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/repository_refs/{resource_id}", json=data)
        return RepositoryRef.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[RepositoryRef]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
