# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .workflow import Workflow, WorkflowList

if TYPE_CHECKING:
    from .client import AmbientClient


class WorkflowAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Workflow:
        resp = self._client._request("POST", "/workflows", json=data)
        return Workflow.from_dict(resp)

    def get(self, resource_id: str) -> Workflow:
        resp = self._client._request("GET", f"/workflows/{resource_id}")
        return Workflow.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> WorkflowList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/workflows", params=params)
        return WorkflowList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Workflow:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/workflows/{resource_id}", json=data)
        return Workflow.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Workflow]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
