# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Task:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    name: str = ""
    project_id: str = ""
    prompt: str = ""
    repo_url: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Task:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            name=data.get("name", ""),
            project_id=data.get("project_id", ""),
            prompt=data.get("prompt", ""),
            repo_url=data.get("repo_url", ""),
        )

    @classmethod
    def builder(cls) -> TaskBuilder:
        return TaskBuilder()


@dataclass(frozen=True)
class TaskList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[Task] = ()

    @classmethod
    def from_dict(cls, data: dict) -> TaskList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Task.from_dict(item) for item in data.get("items", [])],
        )


class TaskBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> TaskBuilder:
        self._data["name"] = value
        return self

    def project_id(self, value: str) -> TaskBuilder:
        self._data["project_id"] = value
        return self

    def prompt(self, value: str) -> TaskBuilder:
        self._data["prompt"] = value
        return self

    def repo_url(self, value: str) -> TaskBuilder:
        self._data["repo_url"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        return dict(self._data)


class TaskPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def name(self, value: str) -> TaskPatch:
        self._data["name"] = value
        return self

    def project_id(self, value: str) -> TaskPatch:
        self._data["project_id"] = value
        return self

    def prompt(self, value: str) -> TaskPatch:
        self._data["prompt"] = value
        return self

    def repo_url(self, value: str) -> TaskPatch:
        self._data["repo_url"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

