# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class WorkflowSkill:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    position: int = 0
    skill_id: str = ""
    workflow_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> WorkflowSkill:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            position=data.get("position", 0),
            skill_id=data.get("skill_id", ""),
            workflow_id=data.get("workflow_id", ""),
        )

    @classmethod
    def builder(cls) -> WorkflowSkillBuilder:
        return WorkflowSkillBuilder()


@dataclass(frozen=True)
class WorkflowSkillList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[WorkflowSkill] = ()

    @classmethod
    def from_dict(cls, data: dict) -> WorkflowSkillList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[WorkflowSkill.from_dict(item) for item in data.get("items", [])],
        )


class WorkflowSkillBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def position(self, value: int) -> WorkflowSkillBuilder:
        self._data["position"] = value
        return self

    def skill_id(self, value: str) -> WorkflowSkillBuilder:
        self._data["skill_id"] = value
        return self

    def workflow_id(self, value: str) -> WorkflowSkillBuilder:
        self._data["workflow_id"] = value
        return self

    def build(self) -> dict:
        if "skill_id" not in self._data:
            raise ValueError("skill_id is required")
        if "workflow_id" not in self._data:
            raise ValueError("workflow_id is required")
        return dict(self._data)


class WorkflowSkillPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def position(self, value: int) -> WorkflowSkillPatch:
        self._data["position"] = value
        return self

    def skill_id(self, value: str) -> WorkflowSkillPatch:
        self._data["skill_id"] = value
        return self

    def workflow_id(self, value: str) -> WorkflowSkillPatch:
        self._data["workflow_id"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

