# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
# Generated: 2026-02-15T12:36:04Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class WorkflowTask:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    position: int = 0
    task_id: str = ""
    workflow_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> WorkflowTask:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            position=data.get("position", 0),
            task_id=data.get("task_id", ""),
            workflow_id=data.get("workflow_id", ""),
        )

    @classmethod
    def builder(cls) -> WorkflowTaskBuilder:
        return WorkflowTaskBuilder()


@dataclass(frozen=True)
class WorkflowTaskList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: List[WorkflowTask] = ()

    @classmethod
    def from_dict(cls, data: dict) -> WorkflowTaskList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[WorkflowTask.from_dict(item) for item in data.get("items", [])],
        )


class WorkflowTaskBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def position(self, value: int) -> WorkflowTaskBuilder:
        self._data["position"] = value
        return self

    def task_id(self, value: str) -> WorkflowTaskBuilder:
        self._data["task_id"] = value
        return self

    def workflow_id(self, value: str) -> WorkflowTaskBuilder:
        self._data["workflow_id"] = value
        return self

    def build(self) -> dict:
        if "task_id" not in self._data:
            raise ValueError("task_id is required")
        if "workflow_id" not in self._data:
            raise ValueError("workflow_id is required")
        return dict(self._data)


class WorkflowTaskPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def position(self, value: int) -> WorkflowTaskPatch:
        self._data["position"] = value
        return self

    def task_id(self, value: str) -> WorkflowTaskPatch:
        self._data["task_id"] = value
        return self

    def workflow_id(self, value: str) -> WorkflowTaskPatch:
        self._data["workflow_id"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

