// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type PermissionAPI struct {
	client *Client
}

func (c *Client) Permissions() *PermissionAPI {
	return &PermissionAPI{client: c}
}

func (a *PermissionAPI) Create(ctx context.Context, resource *types.Permission) (*types.Permission, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal permission: %w", err)
	}
	var result types.Permission
	if err := a.client.do(ctx, http.MethodPost, "/permissions", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *PermissionAPI) Get(ctx context.Context, id string) (*types.Permission, error) {
	var result types.Permission
	if err := a.client.do(ctx, http.MethodGet, "/permissions/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *PermissionAPI) List(ctx context.Context, opts *types.ListOptions) (*types.PermissionList, error) {
	var result types.PermissionList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/permissions", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *PermissionAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Permission, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Permission
	if err := a.client.do(ctx, http.MethodPatch, "/permissions/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *PermissionAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Permission] {
	return NewIterator(func(page int) (*types.PermissionList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
