// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectKeyAPI struct {
	client *Client
}

func (c *Client) ProjectKeys() *ProjectKeyAPI {
	return &ProjectKeyAPI{client: c}
}

func (a *ProjectKeyAPI) Create(ctx context.Context, resource *types.ProjectKey) (*types.ProjectKey, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project_key: %w", err)
	}
	var result types.ProjectKey
	if err := a.client.do(ctx, http.MethodPost, "/project_keys", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectKeyAPI) Get(ctx context.Context, id string) (*types.ProjectKey, error) {
	var result types.ProjectKey
	if err := a.client.do(ctx, http.MethodGet, "/project_keys/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectKeyAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProjectKeyList, error) {
	var result types.ProjectKeyList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/project_keys", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProjectKeyAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/project_keys/"+id, nil, http.StatusNoContent, nil)
}

func (a *ProjectKeyAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ProjectKey] {
	return NewIterator(func(page int) (*types.ProjectKeyList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
