// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectSettingsAPI struct {
	client *Client
}

func (c *Client) ProjectSettings() *ProjectSettingsAPI {
	return &ProjectSettingsAPI{client: c}
}

func (a *ProjectSettingsAPI) Create(ctx context.Context, resource *types.ProjectSettings) (*types.ProjectSettings, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project_settings: %w", err)
	}
	var result types.ProjectSettings
	if err := a.client.do(ctx, http.MethodPost, "/project_settings", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectSettingsAPI) Get(ctx context.Context, id string) (*types.ProjectSettings, error) {
	var result types.ProjectSettings
	if err := a.client.do(ctx, http.MethodGet, "/project_settings/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectSettingsAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProjectSettingsList, error) {
	var result types.ProjectSettingsList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/project_settings", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProjectSettingsAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.ProjectSettings, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ProjectSettings
	if err := a.client.do(ctx, http.MethodPatch, "/project_settings/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectSettingsAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/project_settings/"+id, nil, http.StatusNoContent, nil)
}

func (a *ProjectSettingsAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ProjectSettings] {
	return NewIterator(func(page int) (*types.ProjectSettingsList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
