// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type RepositoryRefAPI struct {
	client *Client
}

func (c *Client) RepositoryRefs() *RepositoryRefAPI {
	return &RepositoryRefAPI{client: c}
}

func (a *RepositoryRefAPI) Create(ctx context.Context, resource *types.RepositoryRef) (*types.RepositoryRef, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal repository_ref: %w", err)
	}
	var result types.RepositoryRef
	if err := a.client.do(ctx, http.MethodPost, "/repository_refs", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryRefAPI) Get(ctx context.Context, id string) (*types.RepositoryRef, error) {
	var result types.RepositoryRef
	if err := a.client.do(ctx, http.MethodGet, "/repository_refs/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryRefAPI) List(ctx context.Context, opts *types.ListOptions) (*types.RepositoryRefList, error) {
	var result types.RepositoryRefList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/repository_refs", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *RepositoryRefAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.RepositoryRef, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.RepositoryRef
	if err := a.client.do(ctx, http.MethodPatch, "/repository_refs/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryRefAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.RepositoryRef] {
	return NewIterator(func(page int) (*types.RepositoryRefList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
