// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionAPI struct {
	client *Client
}

func (c *Client) Sessions() *SessionAPI {
	return &SessionAPI{client: c}
}

func (a *SessionAPI) Create(ctx context.Context, resource *types.Session) (*types.Session, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Get(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodGet, "/sessions/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionList, error) {
	var result types.SessionList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/sessions", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Session, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) UpdateStatus(ctx context.Context, id string, patch map[string]any) (*types.Session, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal status patch: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+id+"/status", body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Start(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions/"+id+"/start", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Stop(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions/"+id+"/stop", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Session] {
	return NewIterator(func(page int) (*types.SessionList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
