// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
// Generated: 2026-02-14T22:04:03Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SkillAPI struct {
	client *Client
}

func (c *Client) Skills() *SkillAPI {
	return &SkillAPI{client: c}
}

func (a *SkillAPI) Create(ctx context.Context, resource *types.Skill) (*types.Skill, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal skill: %w", err)
	}
	var result types.Skill
	if err := a.client.do(ctx, http.MethodPost, "/skills", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SkillAPI) Get(ctx context.Context, id string) (*types.Skill, error) {
	var result types.Skill
	if err := a.client.do(ctx, http.MethodGet, "/skills/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SkillAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SkillList, error) {
	var result types.SkillList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/skills", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SkillAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Skill, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Skill
	if err := a.client.do(ctx, http.MethodPatch, "/skills/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SkillAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Skill] {
	return NewIterator(func(page int) (*types.SkillList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
