// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type TaskAPI struct {
	client *Client
}

func (c *Client) Tasks() *TaskAPI {
	return &TaskAPI{client: c}
}

func (a *TaskAPI) Create(ctx context.Context, resource *types.Task) (*types.Task, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal task: %w", err)
	}
	var result types.Task
	if err := a.client.do(ctx, http.MethodPost, "/tasks", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *TaskAPI) Get(ctx context.Context, id string) (*types.Task, error) {
	var result types.Task
	if err := a.client.do(ctx, http.MethodGet, "/tasks/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *TaskAPI) List(ctx context.Context, opts *types.ListOptions) (*types.TaskList, error) {
	var result types.TaskList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/tasks", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *TaskAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Task, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Task
	if err := a.client.do(ctx, http.MethodPatch, "/tasks/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *TaskAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Task] {
	return NewIterator(func(page int) (*types.TaskList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
