// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: ecd98d82e2cc77423f2816e2990604c2a459e7016461e02b6f40b2b072739a2e
// Generated: 2026-02-14T22:04:03Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type UserAPI struct {
	client *Client
}

func (c *Client) Users() *UserAPI {
	return &UserAPI{client: c}
}

func (a *UserAPI) Create(ctx context.Context, resource *types.User) (*types.User, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal user: %w", err)
	}
	var result types.User
	if err := a.client.do(ctx, http.MethodPost, "/users", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) Get(ctx context.Context, id string) (*types.User, error) {
	var result types.User
	if err := a.client.do(ctx, http.MethodGet, "/users/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) List(ctx context.Context, opts *types.ListOptions) (*types.UserList, error) {
	var result types.UserList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/users", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.User, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.User
	if err := a.client.do(ctx, http.MethodPatch, "/users/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *UserAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/users/"+id, nil, http.StatusNoContent, nil)
}

func (a *UserAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.User] {
	return NewIterator(func(page int) (*types.UserList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
