// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type WorkflowSkillAPI struct {
	client *Client
}

func (c *Client) WorkflowSkills() *WorkflowSkillAPI {
	return &WorkflowSkillAPI{client: c}
}

func (a *WorkflowSkillAPI) Create(ctx context.Context, resource *types.WorkflowSkill) (*types.WorkflowSkill, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal workflow_skill: %w", err)
	}
	var result types.WorkflowSkill
	if err := a.client.do(ctx, http.MethodPost, "/workflow_skills", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *WorkflowSkillAPI) Get(ctx context.Context, id string) (*types.WorkflowSkill, error) {
	var result types.WorkflowSkill
	if err := a.client.do(ctx, http.MethodGet, "/workflow_skills/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *WorkflowSkillAPI) List(ctx context.Context, opts *types.ListOptions) (*types.WorkflowSkillList, error) {
	var result types.WorkflowSkillList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/workflow_skills", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *WorkflowSkillAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.WorkflowSkill, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.WorkflowSkill
	if err := a.client.do(ctx, http.MethodPatch, "/workflow_skills/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *WorkflowSkillAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.WorkflowSkill] {
	return NewIterator(func(page int) (*types.WorkflowSkillList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
