// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 8ab1aa38f80654f4de02c1a997e1ac8d7d502606cbe5ff819abb6fdc2c7c504d
// Generated: 2026-02-15T12:36:04Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type WorkflowAPI struct {
	client *Client
}

func (c *Client) Workflows() *WorkflowAPI {
	return &WorkflowAPI{client: c}
}

func (a *WorkflowAPI) Create(ctx context.Context, resource *types.Workflow) (*types.Workflow, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal workflow: %w", err)
	}
	var result types.Workflow
	if err := a.client.do(ctx, http.MethodPost, "/workflows", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *WorkflowAPI) Get(ctx context.Context, id string) (*types.Workflow, error) {
	var result types.Workflow
	if err := a.client.do(ctx, http.MethodGet, "/workflows/"+id, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *WorkflowAPI) List(ctx context.Context, opts *types.ListOptions) (*types.WorkflowList, error) {
	var result types.WorkflowList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/workflows", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *WorkflowAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Workflow, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Workflow
	if err := a.client.do(ctx, http.MethodPatch, "/workflows/"+id, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *WorkflowAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Workflow] {
	return NewIterator(func(page int) (*types.WorkflowList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
